import assert from 'node:assert/strict';
import { SalesContactSetPrimary, SalesContactChangeEmployment, SalesContactCreateFollowUp, SalesContactDelete } from '../src/actions/sales-contact-lifecycle.action.ts';
import { SalesContactEmploymentJournal, SalesContactChannelDirectoryMirror } from '../src/hooks/sales-contact.hook.ts';
const actor='seller-a',organizationId='org-a',version='2026-10-02T02:00:00.000Z';
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
function fixture({failJournal=false}={}){
 const tables={forge_customer:[{id:'original',name:'原客户',owner_id:actor,responsible_id:actor,organization_id:organizationId},{id:'target',name:'新客户',owner_id:actor,responsible_id:actor,organization_id:organizationId}],forge_contact:[{id:'contact',name:'测试联系人',customer_id:'original',job_title:'采购经理',owner_id:actor,responsible_id:actor,organization_id:organizationId,updated_at:version,created_at:version,employment_status:'active',is_primary:true,employment_revision:0}],forge_contact_channel:[],forge_contact_employment:[],forge_sales_follow_up:[]};let sequence=0;
 const matches=(row,where={})=>Object.entries(where).every(([key,value])=>value&&typeof value==='object'?(!value.$gte||Date.parse(row[key])>=Date.parse(value.$gte))&&(!value.$lt||Date.parse(row[key])<Date.parse(value.$lt)):(row[key]??null)===value);
 const api={object(name){return {async find({where,limit}={}){return structuredClone((tables[name]||[]).filter(row=>matches(row,where)).slice(0,limit??Infinity))},async findOne({where}){return structuredClone((tables[name]||[]).find(row=>matches(row,where))||null)},async insert(values){if(name==='forge_contact_employment'&&failJournal)throw new Error('journal storage unavailable');const row={id:'r'+(++sequence),...values};(tables[name]??=[]).push(row);return structuredClone(row)},async update(values,options={}){const changed=(tables[name]||[]).filter(row=>matches(row,options.where||{id:values.id}));for(const row of changed){const previous=structuredClone(row);Object.assign(row,values,{updated_at:new Date(Date.parse(version)+(++sequence)).toISOString()});if(name==='forge_contact')await new AsyncFunction('ctx',SalesContactEmploymentJournal.body.source)({session:{userId:actor,isSystem:true},previous,input:{id:row.id,...values},result:row,api})}return options.multi?changed.length:changed[0]},async delete({where}){tables[name]=(tables[name]||[]).filter(row=>!matches(row,where))}}},async transaction(callback){const snapshot=structuredClone(tables);try{return await callback()}catch(error){for(const key of Object.keys(tables))delete tables[key];Object.assign(tables,snapshot);throw error}}};
 const run=(action,input,userId=actor)=>new AsyncFunction('ctx',action.body.source)({recordId:'contact',input,session:{userId,organizationId},api});return{tables,api,run};
}
const changed=fixture();await changed.run(SalesContactChangeEmployment,{expected_updated_at:version,employment_status:'transferred',changed_on:'2026-10-02',company_name:'外部新公司',job_title:'供应链经理',note:'本轮异动'});
assert.equal(changed.tables.forge_contact[0].customer_id,'original');assert.equal(changed.tables.forge_contact[0].current_company_name,'外部新公司');assert.equal(changed.tables.forge_contact[0].is_primary,false);assert.equal(changed.tables.forge_contact_employment.length,2);assert.deepEqual(changed.tables.forge_contact_employment.map(row=>row.company_name),['原客户','外部新公司']);
let contact=changed.tables.forge_contact[0];await changed.run(SalesContactChangeEmployment,{expected_updated_at:contact.updated_at,employment_status:'transferred',changed_on:'2026-10-02',current_customer_id:'target',company_name:'忽略的客户端名称',job_title:'供应链经理'});assert.equal(contact.customer_id,'original');assert.equal(contact.current_company_name,'新客户');assert.equal(changed.tables.forge_contact_employment.length,3);
await assert.rejects(changed.run(SalesContactSetPrimary,{expected_updated_at:contact.updated_at}),/非在职/);
const snapshot=structuredClone(changed.tables);await assert.rejects(changed.run(SalesContactChangeEmployment,{expected_updated_at:version,employment_status:'active',changed_on:'2026-10-02'}),/已被修改/);assert.deepEqual(changed.tables,snapshot);
await assert.rejects(changed.run(SalesContactChangeEmployment,{expected_updated_at:contact.updated_at,employment_status:'active',changed_on:'2026-02-30'}),/日期/);
await assert.rejects(changed.run(SalesContactSetPrimary,{expected_updated_at:contact.updated_at},'seller-b'),/本人/);
const rollback=fixture({failJournal:true}),before=structuredClone(rollback.tables);await assert.rejects(rollback.run(SalesContactChangeEmployment,{expected_updated_at:version,employment_status:'resigned',changed_on:'2026-10-02'}),/storage unavailable/);assert.deepEqual(rollback.tables,before);
const longName=fixture();longName.tables.forge_customer[0].name='原'.repeat(255);await longName.run(SalesContactChangeEmployment,{expected_updated_at:version,employment_status:'transferred',changed_on:'2026-10-02',company_name:'新'.repeat(255)});assert.ok(longName.tables.forge_contact_employment.every(row=>row.name.length<=255));assert.equal(longName.tables.forge_contact_employment[1].company_name.length,255);
const follow=fixture(),params={request_key:'follow-1',follow_type:'phone',followed_at:'2026-10-02',content:'确认交期',next_follow_on:'2026-10-05'};const first=await follow.run(SalesContactCreateFollowUp,params);assert.deepEqual(await follow.run(SalesContactCreateFollowUp,params),first);assert.equal(follow.tables.forge_sales_follow_up.length,1);await assert.rejects(follow.run(SalesContactCreateFollowUp,{...params,content:'更换内容'}),/同一请求/);await assert.rejects(follow.run(SalesContactDelete,{expected_updated_at:version}),/业务引用/);assert.equal(follow.tables.forge_contact.length,1);
const mirror=fixture();mirror.tables.forge_contact_channel.push({id:'phone',contact_id:'contact',value:'13900001002',is_primary:true,owner_id:actor,organization_id:organizationId},{id:'email',contact_id:'contact',value:'sample@example.test',owner_id:actor,organization_id:organizationId});await new AsyncFunction('ctx',SalesContactChannelDirectoryMirror.body.source)({input:{contact_id:'contact'},api:mirror.api});assert.equal(mirror.tables.forge_contact[0].channel_summary,'13900001002\nsample@example.test');
console.log('PASS contact lifecycle: immutable original customer, ordered employment history, primary eligibility, stale/owner denial, rollback, follow-up idempotency and reference-safe deletion');
