/** Contact lifecycle dialogs compose the same host primitives as other workspaces. */
export const contactLifecycleRuntime = `
function ContactEmploymentDialog({row,request,onClose,onSaved}){
 const [values,setValues]=React.useState({employment_status:row.employment_status||'active',changed_on:forgeIsoDate(new Date()),current_customer_id:'',company_name:row.current_company_name||'',job_title:row.job_title||'',note:''}),[query,setQuery]=React.useState(''),[options,setOptions]=React.useState([]),[busy,setBusy]=React.useState(false),[loading,setLoading]=React.useState(false),[error,setError]=React.useState('');
 const patch=(field,value)=>setValues(current=>({...current,[field]:value}));
 React.useEffect(()=>{let active=true;const timer=setTimeout(async()=>{setLoading(true);try{const params=new URLSearchParams({$top:'20',$orderby:'name asc'});if(query.trim())params.set('$search',query.trim());const payload=await request('/data/forge_customer?'+params);if(active){setOptions(payload.records||[]);setError('')}}catch(e){if(active)setError(String(e.message||e))}finally{if(active)setLoading(false)}},200);return()=>{active=false;clearTimeout(timer)}},[query]);
 async function save(){setBusy(true);setError('');try{await request('/actions/forge_contact/sales_contact_change_employment/'+encodeURIComponent(row.id),{method:'POST',body:JSON.stringify({params:{...values,expected_updated_at:row.updated_at}})});await onSaved()}catch(e){setError(String(e.message||e))}finally{setBusy(false)}}
 return <CompositeDialog open className="forge-product contact-lifecycle-dialog" title="任职状态与公司异动" busy={busy} onOpenChange={open=>{if(!open)onClose()}} confirmOnDiscard={!!values.note||values.employment_status!==(row.employment_status||'active')} footer={({requestClose})=><ForgeModelDialogFooter busy={busy} requestClose={requestClose} onSave={save} label="确认更新"/>}>
 {error&&<ForgeNotice tone="error">{error}</ForgeNotice>}
 <div className="contact-lifecycle-grid"><label>任职状态 *<ForgeSelectControl aria-label="任职状态" value={values.employment_status} onChange={e=>patch('employment_status',e.target.value)}>{Object.entries(CONTACT_STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</ForgeSelectControl></label><label>异动日期 *<ForgeDateInput aria-label="异动日期" value={values.changed_on} onChange={e=>patch('changed_on',e.target.value)}/></label>
 {values.employment_status==='transferred'&&<><div className="contact-lifecycle-wide"><label>系统内新客户<input className="fp-input" aria-label="搜索系统内新客户" placeholder="搜索客户名称" value={query} onChange={e=>setQuery(e.target.value)}/><ForgeSelectControl aria-label="系统内新客户" value={values.current_customer_id} disabled={loading} onChange={e=>{const selected=options.find(item=>item.id===e.target.value);setValues(current=>({...current,current_customer_id:e.target.value,company_name:selected?.name||current.company_name}))}}><option value="">不选择系统内客户</option>{options.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</ForgeSelectControl></label><span className="fp-secondary">{loading?'正在搜索客户':'按名称搜索，显示前20条匹配客户'}</span></div><label>新公司名称 *<input className="fp-input" aria-label="新公司名称" value={values.company_name} disabled={!!values.current_customer_id} maxLength={255} onChange={e=>patch('company_name',e.target.value)}/></label><label>新职位<input className="fp-input" aria-label="新职位" maxLength={255} value={values.job_title} onChange={e=>patch('job_title',e.target.value)}/></label></>}
 <label className="contact-lifecycle-wide">说明<textarea className="fp-input" aria-label="异动说明" maxLength={500} rows={3} value={values.note} onChange={e=>patch('note',e.target.value)}/><span className="fp-secondary">{values.note.length}/500</span></label></div><p className="fp-secondary">原任职信息保留在任职轨迹中，历史跟进记录继续保留。</p>
 </CompositeDialog>
}
function ContactFollowUpDialog({row,request,onClose,onSaved}){
 const [values,setValues]=React.useState({request_key:crypto.randomUUID(),follow_type:'phone',followed_at:forgeIsoDate(new Date()),next_follow_on:'',content:''}),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');const patch=(field,value)=>setValues(current=>({...current,[field]:value}));
 async function save(){setBusy(true);setError('');try{await request('/actions/forge_contact/sales_contact_create_follow_up/'+encodeURIComponent(row.id),{method:'POST',body:JSON.stringify({params:values})});await onSaved()}catch(e){setError(String(e.message||e))}finally{setBusy(false)}}
 return <CompositeDialog open className="forge-product contact-lifecycle-dialog" title="新增跟进" busy={busy} confirmOnDiscard={!!values.content} onOpenChange={open=>{if(!open)onClose()}} footer={({requestClose})=><ForgeModelDialogFooter busy={busy} requestClose={requestClose} onSave={save} label="保存跟进"/>}>{error&&<ForgeNotice tone="error">{error}</ForgeNotice>}<div className="contact-lifecycle-grid"><label>跟进方式 *<ForgeSelectControl aria-label="跟进方式" value={values.follow_type} onChange={e=>patch('follow_type',e.target.value)}>{Object.entries(CONTACT_FOLLOW_TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</ForgeSelectControl></label><label>跟进日期 *<ForgeDateInput aria-label="跟进日期" value={values.followed_at} onChange={e=>patch('followed_at',e.target.value)}/></label><label>下次跟进<ForgeDateInput aria-label="下次跟进" value={values.next_follow_on} onChange={e=>patch('next_follow_on',e.target.value)}/></label><label className="contact-lifecycle-wide">跟进内容 *<textarea className="fp-input" aria-label="跟进内容" rows={5} maxLength={20000} value={values.content} onChange={e=>patch('content',e.target.value)}/></label></div></CompositeDialog>
}
`;
