import { ContactViews } from '../views/customer.view.js';
import { modelDialogRuntime } from './model-dialog.page.js';
const sections=ContactViews.formViews?.profile?.sections ?? [];
const fields=sections.flatMap(section=>(section.fields ?? []).map(field=>typeof field==='string'?field:field.field));

export const contactProfileRuntime = `${modelDialogRuntime}
const CONTACT_PROFILE_FIELDS=${JSON.stringify(fields)},CONTACT_PROFILE_SECTIONS=${JSON.stringify(sections)};
function ContactProfileEditor({row,channels,currentUserId,customers=[],users=[],onClose,onSaved}){
 const adapter=useAdapter(),controller=React.useRef(null),notesController=React.useRef(null),channelController=React.useRef(null),active=React.useRef(true);
 const [values,setValues]=React.useState(()=>row?Object.fromEntries(CONTACT_PROFILE_FIELDS.map(field=>[field,row[field]??''])):{responsible_id:currentUserId,employment_status:'active',is_primary:false}),[channelDrafts,setChannelDrafts]=React.useState(()=>row?channels.map(channel=>({draftKey:channel.id,values:Object.fromEntries(['channel_type','name','value','is_primary'].map(field=>[field,channel[field]??'']))})):[['mobile','工作手机'],['telephone','办公座机'],['email','工作邮箱']].map(([channel_type,name])=>({draftKey:'initial-'+channel_type,values:{channel_type,name,value:'',is_primary:false}}))),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[summaryCustomer,setSummaryCustomer]=React.useState(null);
 const baseline=React.useRef(JSON.stringify({values,channelDrafts}));
 React.useEffect(()=>{active.current=true;return()=>{active.current=false}},[]);
 const onReady=React.useCallback(value=>{controller.current=value},[]),onNotesReady=React.useCallback(value=>{notesController.current=value},[]),onChannelsReady=React.useCallback(value=>{channelController.current=value},[]);
 const mergeValues=React.useCallback(next=>setValues(current=>({...current,...next})),[]);
 const identityFields=CONTACT_PROFILE_FIELDS.filter(field=>field!=='remarks'),customer=customers.find(item=>item.id===values.customer_id)||(summaryCustomer?.id===values.customer_id?summaryCustomer:null),owner=users.find(item=>item.id===values.responsible_id),statusLabel={active:'在职',transferred:'已跳槽',resigned:'已离职',retired:'已退休',inactive:'停用'}[values.employment_status]||'—';
 React.useEffect(()=>{let current=true;const id=values.customer_id;if(!id||customers.some(item=>item.id===id)){setSummaryCustomer(null);return}ForgeApiRequest(adapter,'/data/forge_customer/'+encodeURIComponent(id)).then(payload=>{if(current)setSummaryCustomer(payload.record||payload.data?.record||payload.data||payload)}).catch(()=>{if(current)setSummaryCustomer({id,name:'客户资料不可读取'})});return()=>{current=false}},[adapter,values.customer_id,customers]);
 const choosePrimary=React.useCallback((key,checked)=>setChannelDrafts(current=>current.map(channel=>({...channel,values:{...channel.values,is_primary:checked?channel.draftKey===key:(channel.draftKey===key?false:channel.values.is_primary)}}))),[]);
 async function save(){if(!controller.current||!notesController.current||!channelController.current)return;const [headerResult,notesResult,channelsResult]=await Promise.all([controller.current.validate(),notesController.current.validate(),channelController.current.validate()]);if(!active.current||!headerResult.valid||!notesResult.valid||!channelsResult.valid)return;setBusy(true);setError('');try{const header={...headerResult.values,...notesResult.values,expected_updated_at:row?.updated_at},savedChannels=channelsResult.draft.rows.map(channel=>({...channel.values,...(channels.some(existing=>existing.id===channel.draftKey)?{id:channel.draftKey}:{})}));await ForgeApiRequest(adapter,'/actions/forge_contact/sales_contact_save'+(row?'/'+encodeURIComponent(row.id):''),{method:'POST',body:JSON.stringify({params:{header_json:JSON.stringify(header),channels_json:JSON.stringify(savedChannels)}})});if(active.current)await onSaved()}catch(e){if(active.current)setError(String(e.message||e))}finally{if(active.current)setBusy(false)}}
 return <CompositeDialog open className="contact-profile-dialog" title={row?'编辑联系人':'新增联系人'} busy={busy} confirmOnDiscard={JSON.stringify({values,channelDrafts})!==baseline.current} onOpenChange={open=>{if(!open)onClose()}} sidebarLabel="联系人摘要" sidebar={<div className="contact-profile-summary"><div className="contact-profile-avatar">{String(values.name||'新').slice(0,1)}</div><strong>{values.name||'新联系人'}</strong><p>{values.job_title||'待填写职位'}</p><span>{statusLabel}</span><h3>客户关系</h3><dl><dt>所属客户</dt><dd>{customer?.name||'待选择'}</dd><dt>决策权重</dt><dd>{values.decision_weight||'待选择'}</dd><dt>维护人</dt><dd>{owner?.name||owner?.display_name||'待选择'}</dd></dl><nav aria-label="联系人表单分区"><a href="#contact-profile-employment">任职资料</a><a href="#contact-profile-channels">联系方式</a><a href="#contact-profile-notes">补充说明</a></nav></div>} footer={({requestClose})=><ForgeModelDialogFooter busy={busy} requestClose={requestClose} onSave={save} label="保存联系人"/>}>
 <style>{'.contact-profile-dialog{--ui-modal-composite-width:var(--ui-surface-contact-edit-dialog-width,960px);--ui-modal-padding-x:21px;--ui-modal-body-padding-y:21px;--ui-dialog-sidebar-width:var(--ui-surface-contact-edit-dialog-sidebar-width,236px);--ui-form-column-gap:14px;--ui-form-row-gap:14px}.contact-profile-dialog section.contact-profile-section+section{margin-top:21px;padding-top:21px;border-top:1px solid hsl(var(--border))}.contact-profile-heading{display:flex;align-items:center;gap:7px;margin:0 0 14px;font-size:12.25px;font-weight:600}.contact-profile-heading>span{padding:3.5px;background:hsl(var(--muted));border-radius:3.5px}.contact-profile-summary{font-size:12.25px}.contact-profile-avatar{display:grid;place-items:center;width:56px;height:56px;border-radius:50%;background:hsl(var(--muted));font-size:21px;margin:0 auto 14px}.contact-profile-summary>strong,.contact-profile-summary>p,.contact-profile-summary>span{display:block;text-align:center}.contact-profile-summary>p{margin:3.5px 0 7px;color:hsl(var(--muted-foreground))}.contact-profile-summary h3{font-size:12.25px;margin:21px 0 14px;border-top:1px solid hsl(var(--border));padding-top:14px}.contact-profile-summary dt{color:hsl(var(--muted-foreground));margin-top:10.5px}.contact-profile-summary dd{margin:3.5px 0 0;overflow-wrap:anywhere}.contact-profile-summary nav{display:grid;gap:7px;border-top:1px solid hsl(var(--border));margin-top:21px;padding-top:14px}.contact-profile-summary nav a{padding:7px;text-decoration:none;color:inherit}.contact-profile-summary nav a:focus-visible{outline:2px solid hsl(var(--ring))}.contact-profile-dialog [data-slot="composite-dialog-main"]{min-width:0}.contact-profile-dialog [data-testid="relationship-column-header"]{background:hsl(var(--muted));padding-top:7px}.contact-profile-dialog [data-testid="relationship-draft-row"]{min-height:var(--ui-surface-contact-channel-row-height,45.5px)}.contact-profile-dialog [data-slot="composite-dialog-sidebar"]{background:hsl(var(--muted)/.3)}@media(max-width:767px){.contact-profile-summary{display:grid;grid-template-columns:42px minmax(0,1fr);gap:3.5px 10.5px;align-items:center}.contact-profile-avatar{width:42px;height:42px;margin:0;grid-row:1/4}.contact-profile-summary>strong,.contact-profile-summary>p,.contact-profile-summary>span{text-align:left;margin:0}.contact-profile-summary h3,.contact-profile-summary dl{display:none}.contact-profile-summary nav{grid-column:1/-1;display:flex;gap:7px;margin-top:7px;padding-top:7px}.contact-profile-summary nav a{padding:3.5px 7px}}'}</style>
 {error&&<ForgeNotice tone="error">{error}</ForgeNotice>}
 <section id="contact-profile-employment" className="contact-profile-section"><h3 className="contact-profile-heading"><span>01</span>任职资料</h3><ObjectForm objectName="forge_contact" dataSource={adapter} mode={row?'edit':'create'} recordId={row?.id} formType="simple" columns={2} sections={CONTACT_PROFILE_SECTIONS.slice(0,1)} fields={identityFields} values={values} onValuesChange={mergeValues} onControllerReady={onReady} showSubmit={false} showCancel={false} showReset={false} submitHandler={data=>data}/></section>
 <section id="contact-profile-channels" className="contact-profile-section"><h3 className="contact-profile-heading"><span>02</span>联系方式</h3><RelationshipCollectionEditor parentObjectName="forge_contact" childObjectName="forge_contact_channel" relationshipField="contact_id" dataSource={adapter} value={channelDrafts} onChange={setChannelDrafts} fields={['channel_type','name','value']} primaryField="is_primary" onPrimaryChange={choosePrimary} fieldWidths={{channel_type:132,name:112}} columns={3} presentation="rows" parentRecord={values} title="星标表示主要联系方式" itemLabel="联系方式" addLabel="添加联系方式" removeLabel="移除" minRows={0} includeRow={channel=>String(channel.values.value||'').trim()!==''} createDraftValues={()=>({channel_type:'mobile',name:'工作手机',is_primary:false})} onControllerReady={onChannelsReady}/></section>
 <section id="contact-profile-notes" className="contact-profile-section"><h3 className="contact-profile-heading"><span>03</span>补充说明</h3><ObjectForm objectName="forge_contact" dataSource={adapter} mode={row?'edit':'create'} recordId={row?.id} formType="simple" columns={1} sections={CONTACT_PROFILE_SECTIONS.slice(1)} fields={['remarks']} values={values} onValuesChange={mergeValues} onControllerReady={onNotesReady} showSubmit={false} showCancel={false} showReset={false} submitHandler={data=>data}/></section>
 </CompositeDialog>
}
`;
