import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const invoiceReversalSource = `
function App(){
  const adapter=useAdapter();
  const today=new Date(Date.now()+8*60*60*1000).toISOString().slice(0,10);
  const [data,setData]=React.useState({loading:true,sales:[],purchase:[],logs:[],receivables:[],payables:[],customerOffsets:[],supplierOffsets:[],customerPrepayments:[],supplierPrepayments:[],error:''}),[busy,setBusy]=React.useState(false),[form,setForm]=React.useState({sales_code:'',purchase_code:'',purchase_number:'',sales_quantity:'',purchase_quantity:'',invoice_on:today,reason:'',offset_reason:''});
  async function request(path,options={}){const headers={'Content-Type':'application/json',...(adapter?.getAuthHeaders?.()||{}),...(options.headers||{})},raw=String(adapter?.baseUrl||''),base=raw.endsWith('/')?raw.slice(0,-1):raw,transport=adapter?.fetchImpl||fetch,r=await transport(base+'/api/v1'+path,{credentials:'include',...options,headers}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error?.message||p.message||'请求失败');return p;}
  async function find(o){return(await request('/data/'+o+'?$top=200')).records||[];}
  async function load(){try{const v=await Promise.all(['forge_sales_invoice','forge_purchase_invoice','forge_invoice_reversal_log','forge_accounts_receivable','forge_accounts_payable','forge_customer_prepayment_offset','forge_supplier_prepayment_offset','forge_customer_prepayment','forge_supplier_prepayment'].map(find));setData({loading:false,sales:v[0],purchase:v[1],logs:v[2],receivables:v[3],payables:v[4],customerOffsets:v[5],supplierOffsets:v[6],customerPrepayments:v[7],supplierPrepayments:v[8],error:''});}catch(e){setData(d=>({...d,loading:false,error:String(e.message||e)}));}}
  React.useEffect(()=>{load();},[]);
  async function invoke(object,action,id,params){setBusy(true);setData(d=>({...d,error:''}));try{await request('/actions/'+object+'/'+action+'/'+id,{method:'POST',body:JSON.stringify({params})});await load();}catch(e){setData(d=>({...d,error:String(e.message||e)}));}finally{setBusy(false);}}
  const money=v=>'¥'+Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),status={issued:'已开票',settled:'已结清',normal:'正常',partially_red_reversed:'部分红冲',red_reversed:'已红冲',red_invoice:'红字发票',unpaid:'未收款',overdue:'已逾期',approved:'已核销',reversed:'已撤回'},css=\`${forgeProductUiCss}div:has(>.forge-invoice-red){max-width:none!important;margin:0!important}.forge-invoice-red+*{display:none}main:has(.forge-invoice-red)>div{padding:0!important}.forge-invoice-red{min-height:100%;background:#f4f6f8;color:#222831;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,sans-serif}.crumb{height:38px;padding:0 22px;display:flex;align-items:center;color:#76808d;font-size:12px;background:#fff;border-bottom:1px solid #e3e7eb}.head{padding:16px 22px;background:#fff;border-bottom:1px solid #e3e7eb}.head h1{font-size:21px;margin:2px 0 5px}.body{padding:18px 22px 40px;max-width:1480px;margin:auto}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#fff;border:1px solid #dfe4e9;border-radius:7px;padding:16px;margin-bottom:14px}.card h2{font-size:15px;margin:0 0 12px}.kpi{font-size:25px;font-weight:650;margin:8px 0}.muted{font-size:12px;color:#76808d}.hint{padding:10px 13px;background:#edf4ff;color:#315b8a;border-radius:5px;margin-bottom:14px}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.field label{display:block;font-size:12px;color:#697481;margin-bottom:5px}.field input{width:100%;box-sizing:border-box;border:1px solid #d4dae1;border-radius:4px;padding:8px}.table{overflow:auto;border:1px solid #e1e5ea;border-radius:5px}.table table{width:100%;border-collapse:collapse;font-size:12px;min-width:1000px}.table th,.table td{padding:9px 10px;border-bottom:1px solid #edf0f3;text-align:left}.table th{background:#f7f8fa;color:#68727f;font-weight:500}.pill{font-size:11px;padding:3px 8px;border-radius:10px;background:#edf4ff;color:#1769e0}.pill.red{background:#ffeded;color:#b42318}.btn{height:32px;border:1px solid #ccd3da;border-radius:4px;background:#fff;color:#29323d;padding:0 11px;margin:2px}.btn.danger{border-color:#d7a4a4;color:#b42318}.btn.primary{background:#1769e0;border-color:#1769e0;color:#fff}.btn:disabled{opacity:.4}.notice{padding:10px 13px;background:#fff3cd;color:#745600;border-radius:5px;margin-bottom:14px}@media(max-width:900px){.cards,.form{grid-template-columns:1fr}.body{padding:10px}}\`;
  if(data.loading)return <div className="forge-product forge-invoice-red"><style>{css}</style><div className="body">正在加载财务冲销数据…</div></div>;
  const salesNormal=data.sales.filter(x=>(x.invoice_type||'normal')==='normal'),purchaseNormal=data.purchase.filter(x=>(x.invoice_type||'normal')==='normal'),activeCustomerOffsets=data.customerOffsets.filter(x=>x.status==='approved'),activeSupplierOffsets=data.supplierOffsets.filter(x=>x.status==='approved');
  return <div className="forge-product forge-invoice-red"><style>{css}</style><div className="body"><ForgePageHeader section="发票管理" title="财务冲销" description="按数量更正未结发票，或撤回预收预付冲抵并恢复往来余额；全部操作保留原记录"/>{data.error&&<div className="notice">{data.error}</div>}<div className="hint">数量红冲当前只接受单明细、未收付、未冲抵、未确认收入且项目未结算的发票。冲抵撤回不移动资金，只恢复预收预付和应收应付累计。</div>
    <div className="cards"><div className="card"><span className="pill">部分红冲</span><div className="kpi">{salesNormal.filter(x=>x.status==='partially_red_reversed').length+purchaseNormal.filter(x=>x.status==='partially_red_reversed').length}</div><div className="muted">仍有有效余额的蓝字发票</div></div><div className="card"><span className="pill red">已红冲</span><div className="kpi">{salesNormal.filter(x=>x.status==='red_reversed').length+purchaseNormal.filter(x=>x.status==='red_reversed').length}</div><div className="muted">已全部冲销的蓝字发票</div></div><div className="card"><span className="pill">有效冲抵</span><div className="kpi">{activeCustomerOffsets.length+activeSupplierOffsets.length}</div><div className="muted">当前仍影响往来余额</div></div><div className="card"><span className="pill">审计记录</span><div className="kpi">{data.logs.length}</div><div className="muted">全额与数量红冲事件</div></div></div>
    <div className="card"><h2>冲销参数</h2><div className="form">{[['销项红字编号','sales_code'],['销项红冲数量','sales_quantity'],['进项红字登记号','purchase_code'],['进项红字发票号','purchase_number'],['进项红冲数量','purchase_quantity'],['红冲原因','reason'],['冲抵撤回原因','offset_reason']].map(x=><div className="field" key={x[1]}><label>{x[0]}</label><input aria-label={x[0]} value={form[x[1]]} onChange={e=>setForm({...form,[x[1]]:e.target.value})}/></div>)}<div className="field"><label>红冲日期</label><ForgeDateInput aria-label="红冲日期"  value={form.invoice_on} onChange={e=>setForm({...form,invoice_on:e.target.value})}/></div></div></div>
    <div className="card"><h2>销项发票</h2><div className="table"><table><thead><tr><th>发票编号</th><th>类型</th><th>原金额</th><th>已红冲</th><th>有效应收</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.sales.map(x=>{const ar=data.receivables.find(a=>a.invoice_id===x.id),eligible=['issued','partially_red_reversed'].includes(x.status)&&x.invoice_type!=='red';return <tr key={x.id}><td>{x.code}</td><td>{x.invoice_type==='red'?'红字':'蓝字'}</td><td>{money(x.total_amount)}</td><td>{money(x.red_reversed_amount)}</td><td>{money(ar?.outstanding_amount)}</td><td><span className={'pill '+(x.status.includes('red')?'red':'')}>{status[x.status]||x.status}</span></td><td><button aria-label={'销项数量红冲 '+x.code} className="btn primary" disabled={busy||!eligible||!form.sales_code.trim()||!(Number(form.sales_quantity)>0)||!form.reason.trim()} onClick={()=>invoke('forge_sales_invoice','sales_invoice_partial_red_reverse',x.id,{code:form.sales_code,invoice_on:form.invoice_on,quantity:Number(form.sales_quantity),reversal_reason:form.reason})}>按数量红冲</button><button className="btn danger" disabled={busy||x.status!=='issued'||x.invoice_type==='red'||!form.sales_code.trim()||!form.reason.trim()} onClick={()=>invoke('forge_sales_invoice','sales_invoice_red_reverse',x.id,{code:form.sales_code+'-FULL',invoice_on:form.invoice_on,reversal_reason:form.reason})}>整单红冲</button></td></tr>})}</tbody></table></div></div>
    <div className="card"><h2>进项发票</h2><div className="table"><table><thead><tr><th>登记编号</th><th>发票号码</th><th>类型</th><th>原金额</th><th>已红冲</th><th>有效应付</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.purchase.map(x=>{const ap=data.payables.find(a=>a.invoice_id===x.id),eligible=['normal','partially_red_reversed'].includes(x.status)&&x.invoice_type!=='red';return <tr key={x.id}><td>{x.code}</td><td>{x.invoice_number}</td><td>{x.invoice_type==='red'?'红字':'蓝字'}</td><td>{money(x.total_amount)}</td><td>{money(x.red_reversed_amount)}</td><td>{money(ap?.outstanding_amount)}</td><td><span className={'pill '+(x.status.includes('red')?'red':'')}>{status[x.status]||x.status}</span></td><td><button aria-label={'进项数量红冲 '+x.code} className="btn primary" disabled={busy||!eligible||!form.purchase_code.trim()||!form.purchase_number.trim()||!(Number(form.purchase_quantity)>0)||!form.reason.trim()} onClick={()=>invoke('forge_purchase_invoice','purchase_invoice_partial_red_reverse',x.id,{code:form.purchase_code,invoice_number:form.purchase_number,invoice_on:form.invoice_on,quantity:Number(form.purchase_quantity),reversal_reason:form.reason})}>按数量红冲</button><button className="btn danger" disabled={busy||x.status!=='normal'||x.invoice_type==='red'||!form.purchase_code.trim()||!form.purchase_number.trim()||!form.reason.trim()} onClick={()=>invoke('forge_purchase_invoice','purchase_invoice_red_reverse',x.id,{code:form.purchase_code+'-FULL',invoice_number:form.purchase_number+'-FULL',invoice_on:form.invoice_on,reversal_reason:form.reason})}>整单红冲</button></td></tr>})}</tbody></table></div></div>
    <div className="card"><h2>预收与预付冲抵</h2><div className="table"><table><thead><tr><th>方向</th><th>冲抵编号</th><th>预收/预付款</th><th>金额</th><th>日期</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.customerOffsets.map(x=><tr key={'c'+x.id}><td>客户预收</td><td>{x.code}</td><td>{data.customerPrepayments.find(p=>p.id===x.prepayment_id)?.code||x.prepayment_id}</td><td>{money(x.amount)}</td><td>{x.offset_on}</td><td><span className="pill">{status[x.status]||x.status}</span></td><td><button aria-label={'撤回客户冲抵 '+x.code} className="btn danger" disabled={busy||x.status!=='approved'||!form.offset_reason.trim()} onClick={()=>invoke('forge_customer_prepayment_offset','customer_prepayment_offset_reverse',x.id,{reversal_reason:form.offset_reason})}>撤回冲抵</button></td></tr>)}{data.supplierOffsets.map(x=><tr key={'s'+x.id}><td>供应商预付</td><td>{x.code}</td><td>{data.supplierPrepayments.find(p=>p.id===x.prepayment_id)?.code||x.prepayment_id}</td><td>{money(x.amount)}</td><td>{x.offset_on}</td><td><span className="pill">{status[x.status]||x.status}</span></td><td><button aria-label={'撤回供应商冲抵 '+x.code} className="btn danger" disabled={busy||x.status!=='approved'||!form.offset_reason.trim()} onClick={()=>invoke('forge_supplier_prepayment_offset','supplier_prepayment_offset_reverse',x.id,{reversal_reason:form.offset_reason})}>撤回冲抵</button></td></tr>)}</tbody></table></div></div>
    <div className="card"><h2>红冲审计</h2><div className="table"><table><thead><tr><th>事件键</th><th>方向</th><th>方式</th><th>红冲金额</th><th>剩余有效金额</th><th>原因</th><th>时间</th></tr></thead><tbody>{data.logs.map(x=><tr key={x.id}><td>{x.event_key}</td><td>{x.direction==='sales'?'销项':'进项'}</td><td>{x.reversal_kind==='partial'?'按数量':'整单'}</td><td>{money(x.amount)}</td><td>{money(x.remaining_amount)}</td><td>{x.reason}</td><td>{x.occurred_at}</td></tr>)}</tbody></table></div></div>
  </div></div>;
}
export default App;
${forgeProductUiRuntime}
`;

export const InvoiceReversalPage = { name: 'page_invoice_reversal', label: '财务冲销', description: '进销项发票整单或按数量红冲、预收预付冲抵撤回与审计追踪', icon: 'receipt-text', type: 'app' as const, kind: 'react' as const, source: invoiceReversalSource };
