import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const source = `
function App(){
  const [tab,setTab]=React.useState('plan');
  const [data,setData]=React.useState({loading:true,projects:[],plans:[],error:''});
  async function request(path){const r=await fetch('/api/v1'+path,{credentials:'include'}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error?.message||p.message||'请求失败');return p;}
  async function find(object){return (await request('/data/'+object+'?$top=200')).records||[];}
  React.useEffect(()=>{Promise.all([find('forge_project'),find('forge_project_plan')]).then(([projects,plans])=>setData({loading:false,projects,plans,error:''})).catch(e=>setData(d=>({...d,loading:false,error:String(e.message||e)})));},[]);
  const css=\`${forgeProductUiCss}div:has(>.forge-project-settings){max-width:none!important;margin:0!important}.forge-project-settings{min-height:100%;background:#f3f5f7;color:#222831;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,sans-serif}.crumb{height:38px;padding:0 22px;display:flex;align-items:center;color:#77818e;font-size:12px;background:#fff;border-bottom:1px solid #e2e6ea}.head{padding:16px 22px;background:#fff;border-bottom:1px solid #e2e6ea}.head h1{font-size:21px;margin:2px 0 5px}.muted{font-size:12px;color:#77818e}.body{padding:18px 22px 40px;max-width:1280px;margin:auto}.tabs{display:flex;gap:8px;border-bottom:1px solid #dfe4e9;margin-bottom:14px}.tabs button{height:38px;border:0;border-bottom:2px solid transparent;background:transparent;padding:0 14px;color:#68727f;cursor:pointer}.tabs button.active{color:#1769e0;border-color:#1769e0;font-weight:600}.card{background:#fff;border:1px solid #dfe4e9;border-radius:7px;padding:16px;margin-bottom:14px}.card h2{font-size:15px;margin:0 0 8px}.status{display:inline-block;padding:3px 8px;border-radius:10px;background:#fff3cd;color:#745600;font-size:11px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.metric{border:1px solid #e1e5ea;border-radius:6px;padding:14px}.metric strong{display:block;font-size:22px;margin:6px 0}.table{overflow:auto;border:1px solid #e1e5ea;border-radius:5px}.table table{width:100%;border-collapse:collapse;font-size:12px}.table th,.table td{padding:9px 10px;border-bottom:1px solid #edf0f3;text-align:left}.table th{background:#f7f8fa;color:#68727f;font-weight:500}.notice{padding:10px 13px;background:#fff3cd;color:#745600;border-radius:5px;margin-bottom:14px}@media(max-width:800px){.grid{grid-template-columns:1fr}.body{padding:10px}}
  \`;
  if(data.loading)return <div className="forge-project-settings"><style>{css}</style><div className="body">正在加载项目配置状态…</div></div>;
  return <div className="forge-project-settings"><style>{css}</style><div className="crumb">项目 / 项目配置中心</div><div className="head"><h1>项目配置中心</h1><div className="muted">统一查看计划模板、交付包模板与工时成本配置；尚未实现的配置动作明确保留为待复刻。</div></div><div className="body">{data.error&&<div className="notice">{data.error}</div>}<div className="tabs"><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>计划模板</button><button className={tab==='delivery'?'active':''} onClick={()=>setTab('delivery')}>交付包模板</button><button className={tab==='cost'?'active':''} onClick={()=>setTab('cost')}>工时成本配置</button></div>{tab==='plan'&&<><div className="card"><h2>计划模板</h2><p className="muted">当前项目计划支持手工创建、系统模板、自定义模板和项目复制四种来源；当前租户没有可供套用的模板记录。</p><span className="status">模板管理待复刻</span></div><div className="card"><h2>现有计划来源</h2><div className="table"><table><thead><tr><th>计划</th><th>项目</th><th>来源</th><th>版本</th><th>状态</th></tr></thead><tbody>{data.plans.length?data.plans.map(x=><tr key={x.id}><td>{x.name||x.code}</td><td>{data.projects.find(p=>p.id===x.project_id)?.code||'—'}</td><td>{x.source||'manual'}</td><td>{x.revision||'—'}</td><td>{x.status||'—'}</td></tr>):<tr><td colSpan="5" className="muted">暂无项目计划记录</td></tr>}</tbody></table></div></div></>}{tab==='delivery'&&<div className="card"><h2>交付包模板</h2><p className="muted">交付验收工作台已支持交付包、客户验收、整改和复验记录，但模板化配置尚未在当前工程中建立数据对象。</p><span className="status">模板管理待复刻</span></div>}{tab==='cost'&&<><div className="grid"><div className="metric"><span className="muted">费率来源</span><strong>工时单录入</strong><span className="muted">当前记录显式保存费率</span></div><div className="metric"><span className="muted">成本生成时点</span><strong>审核通过</strong><span className="muted">审核后进入项目成本池</span></div><div className="metric"><span className="muted">成本对象</span><strong>{data.projects.length}</strong><span className="muted">当前可归集项目数</span></div></div><div className="card"><h2>配置边界</h2><p className="muted">当前已验证的是项目工时填报、审核和人工成本归集规则。角色费率、薪资折算、管理加成和生效期间尚未完成 RISEMAP 同材料复核，因此暂不提供未经证实的配置写入动作。</p><span className="status">规则可见，配置写入待复刻</span></div></>}</div></div>;
}
`;

export const ProjectSettingsPage = { name: 'page_project_settings', label: '项目配置中心', description: '计划模板、交付包模板与工时成本配置状态', icon: 'sliders-horizontal', type: 'app' as const, kind: 'react' as const, source: source + forgeProductUiRuntime };
