import { forgeProductUiCss, forgeProductUiRuntime, forgeProcurementUiCss } from './product-ui.js';

const sharedCss = forgeProductUiCss + forgeProcurementUiCss + `
.forge-iqc .hero{max-width:1520px;margin:0 auto;padding:18px 22px 8px;display:flex;justify-content:space-between;align-items:center}.forge-iqc .hero h1{margin:0;font-size:24px}.forge-iqc .hero p{margin:4px 0 0;color:var(--fp-muted);font-size:12px}.forge-iqc .hero .flow{display:block;margin:0;padding:7px 10px;background:var(--fp-primary-soft);color:var(--fp-primary);border:0}.forge-iqc .toolbar{margin-bottom:12px}.forge-iqc .toolbar input{width:min(420px,100%)}
`;

const pendingInspectionPageSource = `
function App(){
 const [state,setState]=React.useState({loading:true,rows:[],suppliers:{},orders:{},error:''}),[query,setQuery]=React.useState(''),[methods,setMethods]=React.useState({}),[dialog,setDialog]=React.useState(null),[busy,setBusy]=React.useState('');
 async function request(path,options){const response=await fetch('/api/v1'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||payload.message||'请求失败');return payload;}
 async function find(object,where){const filter=where?('&$filter='+encodeURIComponent(JSON.stringify(where))):'';return (await request('/data/'+object+'?$top=100'+filter)).records||[];}
 async function load(){try{const [rows,suppliers,orders]=await Promise.all([find('forge_pending_inspection'),find('forge_supplier'),find('forge_purchase_order')]);setState({loading:false,rows,suppliers:Object.fromEntries(suppliers.map(x=>[x.id,x])),orders:Object.fromEntries(orders.map(x=>[x.id,x])),error:''});}catch(error){setState(s=>({...s,loading:false,error:String(error.message||error)}));}}
 React.useEffect(()=>{load();},[]);
 async function runCreate(row){setBusy(row.id);try{const payload=await request('/actions/forge_pending_inspection/pending_inspection_create_order/'+row.id,{method:'POST',body:JSON.stringify({params:{inspection_method:methods[row.id]||'full'}})});const result=payload.result||payload.data?.result||payload.data||payload;if(!result.id)throw new Error('检验单创建后未返回记录ID');window.location.href='/_console/apps/forge/page/page_purchase_inspection_workspace?id='+encodeURIComponent(result.id);}catch(error){setDialog(d=>d?({...d,error:String(error.message||error)}):d);setState(s=>({...s,error:String(error.message||error)}));setBusy('');}}
 function create(row){setDialog({row,title:'确认生成检验单',subtitle:row.code+' · '+row.item_code,impact:'确认后将为该待检物料生成检验单，并进入检验办理。',error:''});}
 const rows=state.rows.filter(row=>!query||[row.code,row.item_code,row.name,state.suppliers[row.supplier_id]?.name,row.batch_number].some(v=>String(v||'').includes(query))),inspectResult=row=>row.status==='inspected'?'已检验':row.inspection_id?'检验中':'—';
 return <div className="forge-product forge-procurement forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="hero"><div><h1>待检验库存</h1><p>每个物料独立一条待检记录，关联来料检验流程</p></div><div className="flow">下一步操作　检验单　›</div></div><div className="body">{state.error&&<div className="notice">{state.error}</div>}<div className="card"><div className="toolbar"><input aria-label="搜索待检记录" placeholder="搜索待检单号、物料编码、物料名称、供应商、批次号..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn" onClick={()=>window.location.href='/_console/apps/forge/page/page_purchase_arrival_workspace'}>到货登记</button><button className="btn" onClick={()=>window.location.href='/_console/apps/forge/page/page_purchase_inspection_workspace'}>检验单</button><button className="btn" onClick={load}>刷新</button></div><div className="table"><table><thead><tr><th>待检单号</th><th>物料编码</th><th>物料名称</th><th>规格型号</th><th>到货数量</th><th>单位</th><th>批次号</th><th>供应商/客户</th><th>采购合同</th><th>到货日期</th><th>状态</th><th>关联检验单</th><th>检验结果</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.item_code}</td><td>{row.name.replace(/^PIN-\\d{4}-\\d+ /,'')}</td><td>{row.specification} / {row.model}</td><td>{row.arrival_quantity}</td><td>{row.unit_name}</td><td>{row.batch_number||'—'}</td><td>{state.suppliers[row.supplier_id]?.name||'—'}</td><td>{state.orders[row.order_id]?.code||'—'}</td><td>{row.arrived_on||'—'}</td><td><span className="pill">{row.status==='pending'?'待检验':row.status==='inspection_created'?'检验中':row.status==='inspected'?'已检验':'免检'}</span></td><td>{row.inspection_id||'—'}</td><td>{inspectResult(row)}</td><td>{row.status==='pending'?<span><ForgeSelectControl aria-label={row.item_code+' 检验方式'} value={methods[row.id]||'full'} onChange={e=>setMethods(m=>({...m,[row.id]:e.target.value}))}><option value="full">全检</option><option value="sampling">抽检</option></ForgeSelectControl> <button className="btn primary" disabled={busy===row.id} onClick={()=>create(row)}>生成检验单</button></span>:row.inspection_id?<button className="btn" onClick={()=>window.location.href='/_console/apps/forge/page/page_purchase_inspection_workspace?id='+encodeURIComponent(row.inspection_id)}>查看检验单</button>:'—'}</td></tr>)}</tbody></table>{!state.loading&&!rows.length&&<div className="muted" style={{padding:40,textAlign:'center'}}>暂无匹配的待检记录</div>}</div></div>{dialog&&<ForgeDialog open title={dialog.title} subtitle={dialog.subtitle} error={dialog.error} busy={!!busy} confirmLabel="确认生成" onCancel={()=>!busy&&setDialog(null)} onConfirm={()=>runCreate(dialog.row)}><div className="notice">{dialog.impact}</div><div className="muted">请确认待检物料、批次、供应商和检验方式无误。</div></ForgeDialog>}</div></div>;
}
export default App;
${forgeProductUiRuntime}
`;

const purchaseInspectionPageSource = `
${forgeProductUiRuntime}
function App(){
 const id=new URLSearchParams(window.location.search).get('id'),[state,setState]=React.useState({loading:true,rows:[],receipts:{},suppliers:{},record:null,receipt:null,pending:null,supplier:null,order:null,error:''}),[form,setForm]=React.useState({inspected_on:new Date(Date.now()+8*60*60*1000).toISOString().slice(0,10),accepted_quantity:'',inspection_note:''}),[busy,setBusy]=React.useState(false),[query,setQuery]=React.useState('');
 async function request(path,options){const response=await fetch('/api/v1'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||payload.message||'请求失败');return payload;}
 async function read(object,recordId){return (await request('/data/'+object+'/'+recordId)).record;}async function find(object){return (await request('/data/'+object+'?$top=100')).records||[];}
 async function load(){try{if(!id){const [rows,receipts,suppliers]=await Promise.all([find('forge_purchase_inspection'),find('forge_purchase_receipt'),find('forge_supplier')]);setState({loading:false,rows,receipts:Object.fromEntries(receipts.map(x=>[x.id,x])),suppliers:Object.fromEntries(suppliers.map(x=>[x.id,x])),record:null,receipt:null,pending:null,supplier:null,order:null,error:''});return;}const record=await read('forge_purchase_inspection',id),[receipt,pending,supplier,order]=await Promise.all([read('forge_purchase_receipt',record.receipt_id),record.pending_inspection_id?read('forge_pending_inspection',record.pending_inspection_id):Promise.resolve(null),read('forge_supplier',record.supplier_id),read('forge_purchase_order',record.order_id)]);setForm(f=>({...f,accepted_quantity:String(record.total_quantity||0),inspection_note:record.inspection_note||''}));setState({loading:false,rows:[],record,receipt,pending,supplier,order,error:''});}catch(error){setState(s=>({...s,loading:false,error:String(error.message||error)}));}}
 React.useEffect(()=>{load();},[]);
 async function complete(){if(!String(form.inspection_note||'').trim()){setState(s=>({...s,error:'请填写检验结论'}));return}const accepted=Number(form.accepted_quantity);if(!Number.isFinite(accepted)||accepted<0||accepted>Number(state.record.total_quantity)){setState(s=>({...s,error:'合格数量必须在 0 与到货数量之间'}));return}setBusy(true);try{await request('/actions/forge_purchase_inspection/purchase_inspection_complete/'+id,{method:'POST',body:JSON.stringify({params:{inspected_on:form.inspected_on,accepted_quantity:Number(form.accepted_quantity),inspection_note:form.inspection_note.trim()}})});await load();}catch(error){setState(s=>({...s,error:String(error.message||error)}));}finally{setBusy(false);}}
 const visibleRows=state.rows.filter(row=>!query||[row.code,row.item_code,row.name,state.receipts[row.receipt_id]?.code,state.suppliers[row.supplier_id]?.name].some(value=>String(value||'').includes(query)));const receiptCode=id=>state.receipts[id]?.code||id,supplierName=id=>state.suppliers[id]?.name||'—';
 const resultText={pending:'待判定',passed:'合格',partial:'部分合格',rejected:'不合格'},statusText={pending:'待检验',completed:'已完成'};
 if(!id)return <div className="forge-product forge-procurement forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="hero"><div><h1>检验单</h1><p>每条检验单对应一种物料的来料检验</p></div><div className="flow">下一步操作　采购入库　›</div></div><div className="body"><div className="card"><div className="toolbar"><input aria-label="搜索检验单" placeholder="搜索检验单号、到货单号或物料" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn" onClick={load}>刷新</button></div><div className="table"><table><thead><tr><th>检验单号</th><th>到货单号</th><th>物料名称</th><th>供应商/客户</th><th>方式</th><th>总数量</th><th>合格数量</th><th>不合格数量</th><th>结果</th><th>状态</th><th>检验员</th><th>到货日期</th><th>操作</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id}><td>{row.code}</td><td>{receiptCode(row.receipt_id)}</td><td>{row.item_code||row.name}</td><td>{supplierName(row.supplier_id)}</td><td>{row.inspection_method==='sampling'?'抽检':'全检'}</td><td>{row.total_quantity}</td><td>{row.accepted_quantity}</td><td>{row.rejected_quantity}</td><td>{resultText[row.result]||row.result}</td><td>{statusText[row.status]||row.status}</td><td>{row.inspector_id}</td><td>{state.receipts[row.receipt_id]?.arrived_on||'—'}</td><td><button className="btn" onClick={()=>window.location.href=window.location.pathname+'?id='+encodeURIComponent(row.id)}>查看</button></td></tr>)}</tbody></table></div></div></div></div>;
 const record=state.record;if(state.loading)return <div className="forge-product forge-procurement forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="body">正在加载检验单…</div></div>;if(!record)return <div className="forge-product forge-procurement forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="body"><div className="notice">{state.error||'检验单不存在'}</div></div></div>;
 return <div className="forge-product forge-procurement forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="crumb">库存管理 / 检验单 / {record.code}</div><div className="head"><div><span className="pill">{statusText[record.status]}</span><h1>{record.code}</h1><div className="muted">来源 {state.receipt.code} · {record.item_code}</div></div><div className="actions"><button className="btn" onClick={()=>window.location.href='/_console/apps/forge/page/page_pending_inspection_workspace'}>返回待检列表</button>{record.status==='pending'&&<button className="btn primary" disabled={busy} onClick={complete}>完成检验</button>}{record.status==='completed'&&Number(record.accepted_quantity||0)>0&&<button className="btn primary" onClick={()=>window.location.href='/_console/apps/forge/page/page_purchase_inbound_workspace?order='+encodeURIComponent(record.order_id)}>采购入库</button>}</div></div><div className="body">{state.error&&<div className="notice">{state.error}</div>}<div className="card"><div className="details"><div className="value"><small>到货登记</small>{state.receipt.code}</div><div className="value"><small>采购订单</small>{state.order.code}</div><div className="value"><small>供应商</small>{state.supplier.name}</div><div className="value"><small>物料</small>{record.item_code} · {record.name.replace(/^IQC-\\d{4}-\\d+ PIN-\\d{4}-\\d+ /,'')}</div><div className="value"><small>规格型号</small>{record.specification} / {record.model}</div><div className="value"><small>检验方式</small>{record.inspection_method==='sampling'?'抽检':'全检'}</div><div className="value"><small>总数量</small>{record.total_quantity} {record.unit_name}</div><div className="value"><small>批次</small>{record.batch_number||'—'}</div></div></div><div className="card">{record.status==='pending'?<div className="form"><div className="field"><label>检验日期 *</label><ForgeDateInput aria-label="检验日期"  value={form.inspected_on} onChange={e=>setForm({...form,inspected_on:e.target.value})}/></div><div className="field"><label>合格数量 *</label><input aria-label="合格数量" type="number" min="0" max={record.total_quantity} value={form.accepted_quantity} onChange={e=>setForm({...form,accepted_quantity:e.target.value})}/></div><div className="field"><label>不合格数量</label><input value={Math.max(0,Number(record.total_quantity)-Number(form.accepted_quantity||0))} disabled/></div><div className="field wide"><label>检验结论 *</label><textarea aria-label="检验结论" value={form.inspection_note} onChange={e=>setForm({...form,inspection_note:e.target.value})}/></div></div>:<div className="details"><div className="value"><small>检验日期</small>{record.inspected_on}</div><div className="value"><small>合格数量</small>{record.accepted_quantity}</div><div className="value"><small>不合格数量</small>{record.rejected_quantity}</div><div className="value"><small>检验结果</small>{resultText[record.result]}</div><div className="value" style={{gridColumn:'1/-1'}}><small>检验结论</small>{record.inspection_note}</div></div>}</div></div></div>;
}
export default App;`;

export const PendingInspectionWorkspacePage={name:'page_pending_inspection_workspace',label:'待检验库存',description:'按到货物料行跟踪待检状态并生成检验单',icon:'clipboard-clock',type:'app' as const,kind:'react' as const,source:pendingInspectionPageSource};
export const PurchaseInspectionWorkspacePage={name:'page_purchase_inspection_workspace',label:'检验单',description:'逐物料办理采购检验并登记合格与不合格数量',icon:'clipboard-check',type:'app' as const,kind:'react' as const,source:purchaseInspectionPageSource};
