const sharedCss = `div:has(>.forge-iqc){max-width:none!important;margin:0!important}.forge-iqc+*{display:none}div:has(>.forge-iqc)>div:first-child:not(.forge-iqc){display:none}main:has(.forge-iqc)>div{padding:0!important}.forge-iqc{min-height:100%;background:#f5f6f8;color:#20242b;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif}.hero{margin:14px 18px 0;padding:22px 24px;border-radius:8px;background:linear-gradient(110deg,#234d88,#2f7ca1 58%,#5ca4c0);color:#fff;display:flex;justify-content:space-between;align-items:center}.hero h1{font-size:22px;margin:0 0 5px}.hero p{margin:0;font-size:12px;opacity:.86}.flow{font-size:12px;background:rgba(255,255,255,.14);padding:10px 14px;border-radius:5px}.body{padding:14px 18px 32px}.card{background:#fff;border:1px solid #e1e5ea;border-radius:6px;padding:16px;margin-bottom:14px}.toolbar{display:flex;gap:8px;align-items:center;margin-bottom:12px}.toolbar input,.toolbar select,.field input,.field select,.field textarea{border:1px solid #d7dce3;border-radius:4px;padding:8px 10px;background:#fff;box-sizing:border-box}.toolbar input{width:340px}.table{overflow:auto;border:1px solid #e1e5ea;border-radius:5px}.table table{border-collapse:collapse;width:100%;min-width:1180px;font-size:12px}.table th,.table td{padding:10px;border-bottom:1px solid #edf0f3;text-align:left;white-space:nowrap}.table th{background:#f7f8fa;color:#66717f;font-weight:500}.btn{border:1px solid #d6dbe2;background:#fff;border-radius:4px;padding:7px 13px;cursor:pointer}.btn.primary{background:#1769e0;border-color:#1769e0;color:#fff}.btn:disabled{opacity:.5}.pill{display:inline-block;border-radius:4px;background:#eef4ff;color:#1769e0;padding:3px 7px;font-size:11px}.muted{color:#7d8794;font-size:12px}.notice{background:#fff3cd;color:#735600;padding:10px 13px;border-radius:4px;margin-bottom:12px}.crumb{height:38px;display:flex;align-items:center;padding:0 18px;color:#7b8492;font-size:12px;border-bottom:1px solid #e8ebef;background:#fff}.head{background:#fff;padding:14px 20px;border-bottom:1px solid #e2e6eb;display:flex;justify-content:space-between}.head h1{font-size:18px;margin:4px 0}.details{display:grid;grid-template-columns:repeat(4,1fr);gap:10px 24px}.value{border-bottom:1px solid #edf0f3;padding:8px 0}.value small,.field label{display:block;color:#87909c;font-size:12px;margin-bottom:5px}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.field input,.field select,.field textarea{width:100%}.field.wide{grid-column:1/-1}@media(max-width:900px){.hero{margin:8px}.body{padding:8px}.details,.form{grid-template-columns:1fr}.field.wide{grid-column:auto}}`;

const pendingInspectionPageSource = `
function App(){
 const [state,setState]=React.useState({loading:true,rows:[],suppliers:{},orders:{},error:''}),[query,setQuery]=React.useState(''),[methods,setMethods]=React.useState({}),[busy,setBusy]=React.useState('');
 async function request(path,options){const response=await fetch('/api/v1'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||payload.message||'请求失败');return payload;}
 async function find(object,where){const filter=where?('&$filter='+encodeURIComponent(JSON.stringify(where))):'';return (await request('/data/'+object+'?$top=100'+filter)).records||[];}
 async function load(){try{const [rows,suppliers,orders]=await Promise.all([find('forge_pending_inspection'),find('forge_supplier'),find('forge_purchase_order')]);setState({loading:false,rows,suppliers:Object.fromEntries(suppliers.map(x=>[x.id,x])),orders:Object.fromEntries(orders.map(x=>[x.id,x])),error:''});}catch(error){setState(s=>({...s,loading:false,error:String(error.message||error)}));}}
 React.useEffect(()=>{load();},[]);
 async function create(row){setBusy(row.id);try{const payload=await request('/actions/forge_pending_inspection/pending_inspection_create_order/'+row.id,{method:'POST',body:JSON.stringify({params:{inspection_method:methods[row.id]||'full'}})});const result=payload.result||payload.data?.result||payload.data||payload;if(!result.id)throw new Error('检验单创建后未返回记录ID');window.location.href='/_console/apps/forge/page/page_purchase_inspection_workspace?id='+encodeURIComponent(result.id);}catch(error){setState(s=>({...s,error:String(error.message||error)}));setBusy('');}}
 const rows=state.rows.filter(row=>!query||[row.code,row.item_code,row.name,state.suppliers[row.supplier_id]?.name].some(v=>String(v||'').includes(query)));
 return <div className="forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="hero"><div><h1>待检验库存</h1><p>每个物料独立一条待检记录，关联来料检验流程</p></div><div className="flow">下一步操作　检验单　›</div></div><div className="body">{state.error&&<div className="notice">{state.error}</div>}<div className="card"><div className="toolbar"><input aria-label="搜索待检记录" placeholder="搜索待检单号、物料编码、物料名称、供应商、批次号..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn" onClick={load}>刷新</button></div><div className="table"><table><thead><tr><th>待检单号</th><th>物料编码</th><th>物料名称</th><th>规格型号</th><th>到货数量</th><th>单位</th><th>批次号</th><th>供应商/客户</th><th>采购订单</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.item_code}</td><td>{row.name.replace(/^PIN-\\d{4}-\\d+ /,'')}</td><td>{row.specification} / {row.model}</td><td>{row.arrival_quantity}</td><td>{row.unit_name}</td><td>{row.batch_number||'—'}</td><td>{state.suppliers[row.supplier_id]?.name||'—'}</td><td>{state.orders[row.order_id]?.code||'—'}</td><td><span className="pill">{row.status==='pending'?'待检验':row.status==='inspection_created'?'检验中':row.status==='inspected'?'已检验':'免检'}</span></td><td>{row.status==='pending'?<span><select aria-label={row.item_code+' 检验方式'} value={methods[row.id]||'full'} onChange={e=>setMethods(m=>({...m,[row.id]:e.target.value}))}><option value="full">全检</option><option value="sampling">抽检</option></select> <button className="btn primary" disabled={busy===row.id} onClick={()=>create(row)}>生成检验单</button></span>:row.inspection_id?<button className="btn" onClick={()=>window.location.href='/_console/apps/forge/page/page_purchase_inspection_workspace?id='+encodeURIComponent(row.inspection_id)}>查看检验单</button>:'—'}</td></tr>)}</tbody></table>{!state.loading&&!rows.length&&<div className="muted" style={{padding:40,textAlign:'center'}}>暂无匹配的待检记录</div>}</div></div></div></div>;
}
export default App;`;

const purchaseInspectionPageSource = `
function App(){
 const id=new URLSearchParams(window.location.search).get('id'),[state,setState]=React.useState({loading:true,rows:[],record:null,receipt:null,pending:null,supplier:null,order:null,error:''}),[form,setForm]=React.useState({inspected_on:new Date(Date.now()+8*60*60*1000).toISOString().slice(0,10),accepted_quantity:'',inspection_note:''}),[busy,setBusy]=React.useState(false);
 async function request(path,options){const response=await fetch('/api/v1'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||payload.message||'请求失败');return payload;}
 async function read(object,recordId){return (await request('/data/'+object+'/'+recordId)).record;}async function find(object){return (await request('/data/'+object+'?$top=100')).records||[];}
 async function load(){try{if(!id){setState({loading:false,rows:await find('forge_purchase_inspection'),record:null,receipt:null,pending:null,supplier:null,order:null,error:''});return;}const record=await read('forge_purchase_inspection',id),[receipt,pending,supplier,order]=await Promise.all([read('forge_purchase_receipt',record.receipt_id),record.pending_inspection_id?read('forge_pending_inspection',record.pending_inspection_id):Promise.resolve(null),read('forge_supplier',record.supplier_id),read('forge_purchase_order',record.order_id)]);setForm(f=>({...f,accepted_quantity:String(record.total_quantity||0),inspection_note:record.inspection_note||''}));setState({loading:false,rows:[],record,receipt,pending,supplier,order,error:''});}catch(error){setState(s=>({...s,loading:false,error:String(error.message||error)}));}}
 React.useEffect(()=>{load();},[]);
 async function complete(){setBusy(true);try{await request('/actions/forge_purchase_inspection/purchase_inspection_complete/'+id,{method:'POST',body:JSON.stringify({params:{inspected_on:form.inspected_on,accepted_quantity:Number(form.accepted_quantity),inspection_note:form.inspection_note}})});await load();}catch(error){setState(s=>({...s,error:String(error.message||error)}));}finally{setBusy(false);}}
 const resultText={pending:'待判定',passed:'合格',partial:'部分合格',rejected:'不合格'},statusText={pending:'待检验',completed:'已完成'};
 if(!id)return <div className="forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="hero"><div><h1>检验单</h1><p>每条检验单对应一种物料的来料检验</p></div><div className="flow">下一步操作　采购入库　›</div></div><div className="body"><div className="card"><div className="toolbar"><button className="btn" onClick={load}>刷新</button></div><div className="table"><table><thead><tr><th>检验单</th><th>到货单号</th><th>物料</th><th>方式</th><th>总数量</th><th>合格数量</th><th>不合格数量</th><th>结果</th><th>状态</th><th>检验员</th><th>操作</th></tr></thead><tbody>{state.rows.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.receipt_id}</td><td>{row.item_code||row.name}</td><td>{row.inspection_method==='sampling'?'抽检':'全检'}</td><td>{row.total_quantity}</td><td>{row.accepted_quantity}</td><td>{row.rejected_quantity}</td><td>{resultText[row.result]||row.result}</td><td>{statusText[row.status]||row.status}</td><td>{row.inspector_id}</td><td><button className="btn" onClick={()=>window.location.href=window.location.pathname+'?id='+encodeURIComponent(row.id)}>查看</button></td></tr>)}</tbody></table></div></div></div></div>;
 const record=state.record;if(state.loading)return <div className="forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="body">正在加载检验单…</div></div>;if(!record)return <div className="forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="body"><div className="notice">{state.error||'检验单不存在'}</div></div></div>;
 return <div className="forge-iqc"><style>{${JSON.stringify(sharedCss)}}</style><div className="crumb">库存管理 / 检验单 / {record.code}</div><div className="head"><div><span className="pill">{statusText[record.status]}</span><h1>{record.code}</h1><div className="muted">来源 {state.receipt.code} · {record.item_code}</div></div>{record.status==='pending'&&<button className="btn primary" disabled={busy} onClick={complete}>完成检验</button>}</div><div className="body">{state.error&&<div className="notice">{state.error}</div>}<div className="card"><div className="details"><div className="value"><small>到货登记</small>{state.receipt.code}</div><div className="value"><small>采购订单</small>{state.order.code}</div><div className="value"><small>供应商</small>{state.supplier.name}</div><div className="value"><small>物料</small>{record.item_code} · {record.name.replace(/^IQC-\\d{4}-\\d+ PIN-\\d{4}-\\d+ /,'')}</div><div className="value"><small>规格型号</small>{record.specification} / {record.model}</div><div className="value"><small>检验方式</small>{record.inspection_method==='sampling'?'抽检':'全检'}</div><div className="value"><small>总数量</small>{record.total_quantity} {record.unit_name}</div><div className="value"><small>批次</small>{record.batch_number||'—'}</div></div></div><div className="card">{record.status==='pending'?<div className="form"><div className="field"><label>检验日期 *</label><input aria-label="检验日期" type="date" value={form.inspected_on} onChange={e=>setForm({...form,inspected_on:e.target.value})}/></div><div className="field"><label>合格数量 *</label><input aria-label="合格数量" type="number" min="0" max={record.total_quantity} value={form.accepted_quantity} onChange={e=>setForm({...form,accepted_quantity:e.target.value})}/></div><div className="field"><label>不合格数量</label><input value={Math.max(0,Number(record.total_quantity)-Number(form.accepted_quantity||0))} disabled/></div><div className="field wide"><label>检验结论 *</label><textarea aria-label="检验结论" value={form.inspection_note} onChange={e=>setForm({...form,inspection_note:e.target.value})}/></div></div>:<div className="details"><div className="value"><small>检验日期</small>{record.inspected_on}</div><div className="value"><small>合格数量</small>{record.accepted_quantity}</div><div className="value"><small>不合格数量</small>{record.rejected_quantity}</div><div className="value"><small>检验结果</small>{resultText[record.result]}</div><div className="value" style={{gridColumn:'1/-1'}}><small>检验结论</small>{record.inspection_note}</div></div>}</div></div></div>;
}
export default App;`;

export const PendingInspectionWorkspacePage={name:'page_pending_inspection_workspace',label:'待检验库存',description:'按到货物料行跟踪待检状态并生成检验单',icon:'clipboard-clock',type:'app' as const,kind:'react' as const,source:pendingInspectionPageSource};
export const PurchaseInspectionWorkspacePage={name:'page_purchase_inspection_workspace',label:'检验单',description:'逐物料办理采购检验并登记合格与不合格数量',icon:'clipboard-check',type:'app' as const,kind:'react' as const,source:purchaseInspectionPageSource};
