import { Contact } from '../objects/customer.object.js';
import { ContactViews } from '../views/customer.view.js';
import { contactProfileRuntime } from './contact-profile.page.js';
import { contactLifecycleRuntime } from './contact-lifecycle.page.js';
import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css = forgeProductUiCss + `
.sales-contacts .fp-shell{width:min(1500px,100%);padding:var(--ui-page-content-padding-block,17.5px) var(--ui-page-content-padding-inline,21px) 40px}.sales-contacts .fp-title{font-size:var(--ui-page-title-font-size,21px);line-height:var(--ui-surface-contact-title-line-height,28px);font-weight:var(--ui-surface-contact-title-font-weight,700)}.sales-contacts .fp-tab{height:var(--ui-surface-contact-status-tab-height,35px)}.sales-contacts .fp-button,.sales-contacts .fp-page-header .fp-button,.sales-contacts .fp-input,.sales-contacts .fp-picker-trigger{height:var(--ui-control-height,28px);min-height:var(--ui-control-height,28px);border-radius:var(--ui-control-radius,3.5px);font-size:var(--ui-control-font-size,12.25px);line-height:var(--ui-control-line-height,17.5px)}.sales-contacts .fp-metrics{grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--ui-surface-contact-stat-card-gap,10.5px)}.sales-contacts .fp-metric{box-sizing:border-box;height:var(--ui-surface-contact-stat-card-height,61.5px);padding:var(--ui-surface-contact-stat-card-padding-block,12.25px) var(--ui-surface-contact-stat-card-padding-inline,14px);border-radius:var(--ui-surface-contact-stat-card-radius,5.25px)}.sales-contacts .fp-metric-label{font-size:var(--ui-surface-contact-stat-label-font-size,10.5px);line-height:var(--ui-surface-contact-stat-label-line-height,14px);font-weight:var(--ui-surface-contact-stat-label-font-weight,400);margin-bottom:3.5px}.sales-contacts .fp-metric-value{font-size:var(--ui-surface-contact-stat-value-font-size,17.5px);line-height:var(--ui-surface-contact-stat-value-line-height,17.5px);font-weight:var(--ui-surface-contact-stat-value-font-weight,600)}
.sales-contacts .contact-cell{display:flex;align-items:center;gap:10px}.sales-contacts .contact-avatar{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:var(--fp-soft);font-weight:700;flex-shrink:0}.sales-contacts .contact-name{font-weight:600;text-decoration:none;color:inherit}.sales-contacts .kp{display:inline-flex;margin-left:6px;padding:2px 6px;border-radius:999px;font-size:11px;background:var(--fp-soft)}.sales-contacts .channel{display:block;white-space:nowrap}
.sales-contacts .contact-filters{display:grid;grid-template-columns:minmax(260px,1.4fr) minmax(150px,.8fr) minmax(140px,.7fr) auto;gap:8px;align-items:center;padding:12px 16px}.sales-contacts .contact-filters>*{min-width:0}.sales-contacts .contact-filters .fp-input,.sales-contacts .contact-filters .fp-picker-trigger,.sales-contacts .contact-filters .fp-button{height:var(--ui-control-height,28px);min-height:var(--ui-control-height,28px)}.sales-contacts .contact-filter-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;white-space:nowrap}.sales-contacts .contact-actions{display:flex;align-items:center;gap:4px}.sales-contacts .contact-actions .fp-icon-button{width:28px;height:28px;min-height:28px}
.sales-contacts .contact-table-region{position:relative;min-height:90px}.sales-contacts .contact-table-loading{position:absolute;inset:0;z-index:30;display:flex;align-items:center;justify-content:center;background:var(--fp-surface)}.sales-contacts .contacts-record-table{border:0}.sales-contacts .contacts-record-table th{font-size:var(--ui-table-header-font-size,10.5px);height:var(--ui-surface-contact-table-header-height,32px);padding:var(--ui-surface-contact-table-header-padding-block,8.75px) var(--ui-surface-contact-table-header-padding-inline,14px);line-height:var(--ui-table-header-line-height,14px)}.sales-contacts .contacts-record-table td{font-size:var(--ui-surface-contact-table-cell-font-size,14px);line-height:var(--ui-surface-contact-table-cell-line-height,21px);padding:10.5px 14px;vertical-align:middle}.sales-contacts .contacts-record-table tbody tr{height:var(--ui-surface-contact-table-row-min-height,57.8px)}.sales-contacts .contacts-record-table .contact-secondary-value{font-size:12.25px;line-height:17.5px}.sales-contacts .contacts-record-table .fp-secondary,.sales-contacts .contacts-record-table .channel{font-size:10.5px;line-height:14px}.sales-contacts .contacts-record-table .fp-status{font-size:10.5px;line-height:14px}.sales-contacts.compact .contacts-record-table td{padding-top:6px;padding-bottom:6px}.sales-contacts .contact-count{padding:10px 16px;font-size:12px;color:var(--fp-muted);border-top:1px solid var(--fp-line)}.sales-contacts .transfer-actions{display:grid;gap:10px}
.contact-lifecycle-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.contact-lifecycle-grid label{display:grid;gap:7px;font-size:12px}.contact-lifecycle-wide{grid-column:1/-1}.contact-lifecycle-grid .fp-picker,.contact-lifecycle-grid .fp-date-picker{width:100%}.contact-lifecycle-grid .fp-picker-trigger{width:100%}
@media(max-width:1200px){.sales-contacts .fp-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.sales-contacts .contact-filters{grid-template-columns:repeat(3,minmax(0,1fr))}.sales-contacts .contact-filters .fp-search{grid-column:1/-1}}
@media(max-width:760px){.sales-contacts .fp-shell{padding-top:10px}.sales-contacts .contact-filters{grid-template-columns:1fr 1fr}.sales-contacts .contact-filters .fp-search,.sales-contacts .contact-filter-actions{grid-column:1/-1}.sales-contacts .contact-filter-actions{justify-content:flex-start}.contact-lifecycle-grid{grid-template-columns:1fr}}
@media(max-width:520px){.sales-contacts .fp-metrics,.sales-contacts .contact-filters{grid-template-columns:1fr}.sales-contacts .contact-filters .fp-search{grid-column:auto}}
`;
const source = `${contactProfileRuntime}
const CONTACT_STATUS={active:'在职',transferred:'已跳槽',resigned:'已离职',retired:'已退休',inactive:'停用'},CONTACT_FOLLOW_TYPES={phone:'电话',wechat:'微信',email:'邮件',onsite_visit:'上门拜访',customer_visit:'客户来访',online_meeting:'线上会议',demo:'产品演示',proposal:'方案沟通',negotiation:'商务谈判',other:'其他'},CONTACT_VIEW=${JSON.stringify(ContactViews.list)},CONTACT_GENDER=${JSON.stringify(Object.fromEntries((Contact.fields.gender.options ?? []).map(option=>[option.value,option.label])))},CONTACT_WEIGHT=${JSON.stringify(Object.fromEntries((Contact.fields.decision_weight.options ?? []).map(option=>[option.value,option.label])))};
${contactLifecycleRuntime}
function App(){
 const adapter=useAdapter(),initial=React.useRef(new URLSearchParams(location.search)),sequence=React.useRef(0);
 const [state,setState]=React.useState({loading:true,currentUserId:'',contacts:[],channels:[],customers:[],users:[],total:0,counts:{},error:''}),[tab,setTab]=React.useState(initial.current.get('status')||'all'),[q,setQ]=React.useState(initial.current.get('search')||''),[job,setJob]=React.useState(initial.current.get('job')||''),[owner,setOwner]=React.useState(initial.current.get('owner')||'all'),[compact,setCompact]=React.useState(false),[page,setPage]=React.useState(()=>{const value=Number(initial.current.get('p'));return Number.isSafeInteger(value)&&value>0?value:1}),[pageSize,setPageSize]=React.useState(CONTACT_VIEW.pagination.pageSize),[sort,setSort]=React.useState([{field:'created_at',order:'desc'}]),[revision,setRevision]=React.useState(0),[dialog,setDialog]=React.useState(null),[transferOpen,setTransferOpen]=React.useState(false),[busy,setBusy]=React.useState(false),[toast,setToast]=React.useState('');
 const request=React.useCallback((path,options={})=>ForgeApiRequest(adapter,path,options),[adapter]);
 const rows=p=>p?.records||p?.data?.records||[],total=p=>Number(p?.total??p?.data?.total??rows(p).length),status=r=>r.employment_status||'active';
 function query(filter,limit=pageSize,offset=(page-1)*pageSize,expanded=false){const params=new URLSearchParams({$top:String(limit),$skip:String(offset),$count:'true'});if(filter&&Object.keys(filter).length)params.set('$filter',JSON.stringify(filter));params.set('$orderby',sort.map(item=>item.field+' '+item.order).join(','));if(expanded)params.set('$expand','customer_id,responsible_id');return params}
 function filter(){const parts=[];if(tab!=='all')parts.push({employment_status:tab});if(owner!=='all')parts.push({responsible_id:owner==='mine'?state.currentUserId:owner});if(job.trim())parts.push({$or:['job_title','department'].map(field=>({[field]:{$icontains:job.trim()}}))});if(q.trim())parts.push({$or:CONTACT_VIEW.searchableFields.map(field=>({[field]:{$icontains:q.trim()}}))});return parts.length?{$and:parts}:{}}
 async function allRows(object,where){const result=[];let skip=0;for(;;){const params=new URLSearchParams({$top:'100',$skip:String(skip),$count:'true'});if(where)params.set('$filter',JSON.stringify(where));const payload=await request('/data/'+object+'?'+params),batch=rows(payload);result.push(...batch);skip+=batch.length;if(!batch.length||skip>=total(payload))return result}}
 React.useEffect(()=>{const params=new URLSearchParams(location.search);for(const [key,value]of [['status',tab==='all'?'':tab],['search',q],['job',job],['owner',owner==='all'?'':owner],['p',page===1?'':String(page)]]){if(value)params.set(key,value);else params.delete(key)}history.replaceState(history.state,'',location.pathname+(params.size?'?'+params:''))},[tab,q,job,owner,page]);
 React.useEffect(()=>{let active=true;request('/auth/get-session').then(session=>{const user=session.user||session.session?.user;if(!user?.id)throw new Error('登录已失效，请重新登录');if(active)setState(current=>({...current,currentUserId:user.id,users:[user]}))}).catch(e=>{if(active)setState(current=>({...current,loading:false,error:String(e.message||e)}))});return()=>{active=false}},[request]);
 React.useEffect(()=>{if(!state.currentUserId)return;let active=true;const ticket=++sequence.current;setState(current=>({...current,loading:true,error:''}));const timer=setTimeout(async()=>{try{const payload=await request('/data/forge_contact?'+query(filter(),pageSize,(page-1)*pageSize,true));const contactRows=rows(payload),contacts=contactRows.map(row=>({...row,customer_id:typeof row.customer_id==='object'?row.customer_id?.id:row.customer_id,responsible_id:typeof row.responsible_id==='object'?row.responsible_id?.id:row.responsible_id,customerLabel:typeof row.customer_id==='object'?row.customer_id?.name:row.customer_name,ownerLabel:typeof row.responsible_id==='object'?(row.responsible_id?.name||row.responsible_id?.display_name):'',statusLabel:CONTACT_STATUS[row.employment_status||'active']})),grandTotal=total(payload);if(page>1&&(page-1)*pageSize>=grandTotal){if(active)setPage(Math.max(1,Math.ceil(grandTotal/pageSize)));return}const channels=contacts.length?await allRows('forge_contact_channel',{contact_id:{$in:contacts.map(row=>row.id)}}):[];if(!active||ticket!==sequence.current)return;const customers=contactRows.filter(row=>row.customer_id&&typeof row.customer_id==='object').map(row=>row.customer_id),users=contactRows.filter(row=>row.responsible_id&&typeof row.responsible_id==='object').map(row=>row.responsible_id);setState(current=>({...current,loading:false,contacts,channels,customers,users:[...new Map([...current.users,...users].map(item=>[item.id,item])).values()],total:grandTotal,error:''}))}catch(e){if(active&&ticket===sequence.current)setState(current=>({...current,loading:false,error:String(e.message||e)}))}},200);return()=>{active=false;clearTimeout(timer)}},[state.currentUserId,tab,q,job,owner,page,pageSize,JSON.stringify(sort),revision,request]);
 React.useEffect(()=>{if(!state.currentUserId)return;let active=true;Promise.all(['all',...Object.keys(CONTACT_STATUS),'kp'].map(async key=>{const where=key==='all'?{}:key==='kp'?{is_primary:true}:{employment_status:key};const payload=await request('/data/forge_contact?'+query(where,1,0));return[key,total(payload)]})).then(pairs=>{if(active)setState(current=>({...current,counts:Object.fromEntries(pairs)}))}).catch(e=>{if(active)setState(current=>({...current,error:String(e.message||e)}))});return()=>{active=false}},[state.currentUserId,revision,request]);
 const refresh=()=>setRevision(value=>value+1),channelsOf=id=>state.channels.filter(row=>row.contact_id===id).sort((a,b)=>Number(b.is_primary===true)-Number(a.is_primary===true)||String(a.id).localeCompare(String(b.id))),detailUrl=row=>'/_console/apps/com.inoforge.forge.sales/forge_contact/'+encodeURIComponent(row.id);
 async function saved(message){setDialog(null);setToast(message);refresh()}
 async function primary(row){setBusy(true);try{await request('/actions/forge_contact/sales_contact_set_primary/'+encodeURIComponent(row.id),{method:'POST',body:JSON.stringify({params:{expected_updated_at:row.updated_at}})});setToast('已设为主要联系人');refresh()}catch(e){setToast('');setState(current=>({...current,error:String(e.message||e)}))}finally{setBusy(false)}}
 async function remove(){setBusy(true);try{await request('/actions/forge_contact/sales_contact_delete/'+encodeURIComponent(dialog.row.id),{method:'POST',body:JSON.stringify({params:{expected_updated_at:dialog.row.updated_at}})});await saved('联系人已删除')}catch(e){setDialog(current=>({...current,error:String(e.message||e)}))}finally{setBusy(false)}}
 async function exportCsv(mode){setBusy(true);try{const records=mode==='page'?state.contacts:await allRows('forge_contact',filter()),head=['联系人','性别','职位','部门','所属公司','任职状态','决策权重','联系方式','主要联系人'],quote=String.fromCharCode(34),csv=[head,...records.map(row=>[row.name,CONTACT_GENDER[row.gender]||row.gender||'',row.job_title||'',row.department||'',row.customerLabel||row.customer_name||'',CONTACT_STATUS[status(row)],CONTACT_WEIGHT[row.decision_weight]||row.decision_weight||'',row.channel_summary||channelsOf(row.id).map(item=>item.value).join('；'),row.is_primary?'是':'否'])].map(line=>line.map(value=>quote+String(value??'').split(quote).join(quote+quote)+quote).join(',')).join(String.fromCharCode(10)),url=URL.createObjectURL(new Blob([String.fromCharCode(65279)+csv],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download='联系人管理-'+forgeIsoDate(new Date())+'.csv';anchor.click();URL.revokeObjectURL(url);setTransferOpen(false);setToast('已导出 '+records.length+' 条联系人记录')}catch(e){setState(current=>({...current,error:String(e.message||e)}))}finally{setBusy(false)}}
 const cell={name:(value,row)=><div className="contact-cell"><span className="contact-avatar">{String(value||'联').slice(0,1)}</span><div><a className="contact-name" title={row.name} href={detailUrl(row)}>{value}</a>{row.is_primary&&<span className="kp">KP</span>}</div></div>,gender:value=>CONTACT_GENDER[value]||value||'—',job_title:(value,row)=><>{value||'—'}<div className="fp-secondary">{row.department||'—'}</div></>,customer_id:(_value,row)=><>{row.customerLabel||row.customer_name||'—'}{row.current_company_name&&row.current_company_name!==(row.customerLabel||row.customer_name)&&<div className="fp-secondary">现：{row.current_company_name}</div>}</>,employment_status:value=><ForgeStatus value={value||'active'} label={CONTACT_STATUS[value||'active']}/>,decision_weight:value=>CONTACT_WEIGHT[value]||value||'—',channel_summary:(_value,row)=>channelsOf(row.id).length?channelsOf(row.id).map(item=><span className="channel" key={item.id}>{item.is_primary?'★ ':''}{item.value}</span>):'—',responsible_id:(_value,row)=>row.ownerLabel||state.users.find(item=>item.id===row.responsible_id)?.name||'—'};
 const columns=CONTACT_VIEW.columns.map(column=>({accessorKey:({customer_id:'customerLabel',responsible_id:'ownerLabel',employment_status:'statusLabel'})[column.field]||column.field,header:column.label,width:column.width,cellClassName:column.field==='name'?'':'contact-secondary-value',cell:column.field==='employment_status'?(_value,row)=><ForgeStatus value={status(row)} label={CONTACT_STATUS[status(row)]}/>:cell[column.field]})).concat([{accessorKey:'actions',header:'操作',width:182,sortable:false,className:'sticky right-0 z-20',cellClassName:'sticky right-0 z-10 bg-background',cell:(_value,row)=><div className="contact-actions">{!row.is_primary&&<button className="fp-icon-button" aria-label={'设为'+row.name+'的主要联系人'} title="设为主要联系人" disabled={busy} onClick={()=>primary(row)}>☆</button>}<button className="fp-icon-button" aria-label={'标记'+row.name+'任职异动'} title="任职异动" onClick={()=>setDialog({kind:'employment',row})}>⇄</button><button className="fp-icon-button" aria-label={'为'+row.name+'新增跟进'} title="新增跟进" onClick={()=>setDialog({kind:'followup',row})}>＋</button><button className="fp-icon-button" aria-label={'编辑'+row.name} title="编辑" onClick={()=>setDialog({kind:'edit',row})}>✎</button><button className="fp-icon-button" aria-label={'删除'+row.name} title="删除" onClick={()=>setDialog({kind:'delete',row,error:''})}>×</button></div>}]);
 const counts=state.counts,metric=value=>value===undefined?'—':value;
 return <div className={'forge-product sales-contacts '+(compact?'compact':'')}><style>{${JSON.stringify(css)}}</style><div className="fp-shell"><ForgePageHeader section="CRM客户管理 / 联系人管理" title="联系人管理" actions={<><button className="fp-button primary" onClick={()=>setDialog({kind:'edit',row:null})}>＋ 新增联系人</button><button className="fp-button" onClick={()=>setTransferOpen(true)}>⇅ 导入/导出⌄</button></>}/>{state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<ForgeNotice tone="success" onClose={()=>setToast('')}>{toast}</ForgeNotice>}
 <div className="fp-metrics">{[['联系人总数',counts.all],['在职',counts.active],['不在原公司',counts.transferred===undefined?undefined:counts.transferred+counts.resigned+counts.retired],['关键决策人 KP',counts.kp]].map(([label,value])=><div className="fp-metric" key={label}><div className="fp-metric-label">{label}</div><div className="fp-metric-value">{metric(value)}</div></div>)}</div>
 <section className="fp-card"><div className="fp-tabs">{[['all','全部'],...Object.entries(CONTACT_STATUS)].map(([value,label])=><button key={value} className={'fp-tab '+(tab===value?'active':'')} onClick={()=>{setTab(value);setPage(1)}}>{label} {metric(counts[value])}</button>)}</div><div className="contact-filters"><input className="fp-input fp-search" aria-label="搜索联系人" placeholder="搜索姓名、公司、电话、邮箱" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><input className="fp-input" aria-label="按职务筛选联系人" placeholder="筛选职务" value={job} onChange={e=>{setJob(e.target.value);setPage(1)}}/><ForgeSelectControl aria-label="维护人" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}}><option value="all">全部维护人</option><option value="mine">本人</option>{state.users.filter(item=>item.id!==state.currentUserId).map(item=><option key={item.id} value={item.id}>{item.name||item.display_name||'维护人'}</option>)}</ForgeSelectControl><div className="contact-filter-actions"><button className="fp-button" onClick={()=>{setQ('');setJob('');setOwner('all');setPage(1)}}>清空筛选</button><button className="fp-icon-button" aria-label="刷新联系人数据" onClick={refresh}>↻</button><button className="fp-icon-button" aria-label={compact?'切换为标准行高':'切换为紧凑行高'} onClick={()=>setCompact(value=>!value)}>≡</button></div></div>
 <div className="contact-table-region" aria-busy={state.loading}><div inert={state.loading?'':undefined}><RecordTable schema={{type:'data-table',className:'contacts-record-table',columns,data:state.contacts,searchable:false,exportable:false,selectable:false,reorderableColumns:false,manualPagination:true,page,pageSize,pageSizeOptions:[20,50,100],rowCount:state.total,onPageChange:setPage,onPageSizeChange:value=>{setPageSize(value);setPage(1)},manualSorting:true,sort,onSortChange:value=>{setSort(value.length?value.map(item=>({...item,field:({customerLabel:'customer_id',ownerLabel:'responsible_id',statusLabel:'employment_status'})[item.field]||item.field})):[{field:'created_at',order:'desc'}]);setPage(1)}}}/></div>{state.loading&&<div className="contact-table-loading"><ForgeLoading label="正在加载联系人"/></div>}</div><div className="contact-count">共 {state.total} 条记录 · 每页 {pageSize} 条</div></section></div>
 {dialog?.kind==='edit'&&<ContactProfileEditor key={dialog.row?.id||'new'} row={dialog.row} channels={dialog.row?channelsOf(dialog.row.id):[]} currentUserId={state.currentUserId} customers={state.customers} users={state.users} onClose={()=>setDialog(null)} onSaved={()=>saved('联系人已保存')}/>}
 {dialog?.kind==='employment'&&<ContactEmploymentDialog row={dialog.row} request={request} onClose={()=>setDialog(null)} onSaved={()=>saved('任职状态已更新')}/>}
 {dialog?.kind==='followup'&&<ContactFollowUpDialog row={dialog.row} request={request} onClose={()=>setDialog(null)} onSaved={()=>saved('跟进已保存')}/>}
 <ForgeDialog open={dialog?.kind==='delete'} title="确认删除联系人" subtitle={dialog?.row?.name} error={dialog?.error} busy={busy} danger confirmLabel="确认删除" onCancel={()=>!busy&&setDialog(null)} onConfirm={remove}><div className="fp-dialog-impact">删除后同时移除联系方式和任职轨迹，且无法恢复；已有业务引用的联系人不能删除。</div></ForgeDialog>
 <ForgeDialog open={transferOpen} title="导入 / 导出联系人" busy={busy} confirmLabel="关闭" onCancel={()=>setTransferOpen(false)} onConfirm={()=>setTransferOpen(false)}><div className="transfer-actions"><button className="fp-button" onClick={()=>location.href='/_console/apps/com.inoforge.forge.sales/forge_contact'}>批量导入</button><button className="fp-button" disabled={busy||!state.contacts.length} onClick={()=>exportCsv('page')}>导出当前页</button><button className="fp-button" disabled={busy||!state.total} onClick={()=>exportCsv('all')}>导出全部筛选结果</button></div></ForgeDialog></div>
}
export default App;${forgeProductUiRuntime}`;

export const SalesContactsPage={name:'page_sales_contacts',label:'联系人管理',description:'管理联系人资料、任职轨迹与跟进',icon:'contact',type:'app' as const,kind:'react' as const,source};
