import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css = forgeProductUiCss + `
.sales-customers .fp-shell{width:min(1540px,100%);padding-top:20px}
.sales-customers .fp-table{min-width:1320px}
.sales-customers .customer-name{font-weight:650}
.sales-customers .scope-note{padding:10px 16px;border-bottom:1px solid var(--fp-line);color:var(--fp-muted);font-size:12px}
.sales-customers .capability-strip{display:flex;gap:8px;flex-wrap:wrap;padding:0 16px 14px}
.sales-customers .capability-chip{border:1px dashed var(--fp-line);border-radius:999px;padding:5px 10px;color:var(--fp-muted);font-size:12px;background:var(--fp-soft)}
.sales-customers .fp-tab[aria-disabled="true"]{cursor:default;color:var(--fp-muted);opacity:.72}
.sales-customers .form-section{margin:0 0 18px;padding:14px;border:1px solid var(--fp-line);border-radius:12px;background:var(--fp-surface)}
.sales-customers .form-section:last-child{margin-bottom:0}
.sales-customers .form-section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}
.sales-customers .form-section-title{font-size:14px;font-weight:700}
.sales-customers .form-section-hint{font-size:12px;color:var(--fp-muted);margin-top:3px}
.sales-customers .fp-modal{width:min(920px,calc(100vw - 32px))}
.sales-customers .fp-modal-body{max-height:70vh;overflow:auto}
@media(max-width:760px){.sales-customers .fp-shell{padding-top:10px}.sales-customers .form-section{padding:12px}}
`;

const source = `
const css=${JSON.stringify(css)};
function App(){
 const adapter=useAdapter();
 const [state,setState]=React.useState({loading:true,customers:[],contacts:[],channels:[],users:[],categories:[],levels:[],followups:[],orders:[],error:''});
 const [scope,setScope]=React.useState('all'),[q,setQ]=React.useState(''),[category,setCategory]=React.useState('all'),[owner,setOwner]=React.useState('all'),[type,setType]=React.useState('all'),[level,setLevel]=React.useState('all'),[page,setPage]=React.useState(1),[dialog,setDialog]=React.useState(null),[busy,setBusy]=React.useState(false),[toast,setToast]=React.useState('');
 async function request(path,options={}){const headers={'Content-Type':'application/json',...(adapter?.getAuthHeaders?.()||{}),...(options.headers||{})},raw=String(adapter?.baseUrl||''),base=raw.endsWith('/')?raw.slice(0,-1):raw,transport=adapter?.fetchImpl||fetch,response=await transport(base+'/api/v1'+path,{credentials:'include',...options,headers}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||payload.message||'请求失败');return payload}
 const unpack=p=>p?.record||p?.data?.record||p?.data||p;
 const rows=p=>p?.records||p?.data?.records||p?.data||[];
 async function find(name){try{return rows(await request('/data/'+name+'?$top=500'))}catch{return[]}}
 async function create(name,values){return unpack(await request('/data/'+name,{method:'POST',body:JSON.stringify(values)}))}
 async function load(){setState(s=>({...s,loading:true,error:''}));try{const [customers,contacts,channels,users,categories,levels,followups,orders]=await Promise.all(['forge_customer','forge_contact','forge_contact_channel','sys_user','forge_customer_category','forge_customer_level','forge_sales_follow_up','forge_sales_order'].map(find));setState({loading:false,customers,contacts,channels,users,categories,levels,followups,orders,error:''})}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}))}}
 React.useEffect(()=>{load()},[]);
 const user=id=>{const r=state.users.find(x=>x.id===id);return r?.name||r?.display_name||r?.email||'—'},cat=id=>state.categories.find(x=>x.id===id)?.name||'—',lvl=id=>state.levels.find(x=>x.id===id)?.name||'—',money=v=>'¥'+Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:2}),current=state.users.find(x=>String(x.name||x.display_name||'').includes('金一涛'))||state.users.find(x=>String(x.name||x.display_name||'').includes('Dev'))||state.users[0]||{};
 function primaryContact(id){return state.contacts.find(x=>x.customer_id===id&&x.is_primary)||state.contacts.find(x=>x.customer_id===id)}
 function phone(id){const c=primaryContact(id);return c?(state.channels.find(x=>x.contact_id===c.id&&['mobile','telephone'].includes(x.channel_type))?.value||'—'):'—'}
 function latest(list,key){return [...list].sort((a,b)=>String(b[key]||b.updated_at||'').localeCompare(String(a[key]||a.updated_at||'')))[0]}
 function lastFollow(id){const r=latest(state.followups.filter(x=>x.customer_id===id),'followed_at');return r?.followed_at||'—'}
 function nextVisit(id){const r=latest(state.followups.filter(x=>x.customer_id===id&&x.next_follow_on),'next_follow_on');return r?.next_follow_on||'—'}
 function lastTrade(id){const r=latest(state.orders.filter(x=>x.customer_id===id),'updated_at');return r?.updated_at?String(r.updated_at).slice(0,10):'—'}
 const filtered=state.customers.filter(r=>(scope==='all'||r.responsible_id===current.id)&&(category==='all'||r.category_id===category)&&(owner==='all'||r.responsible_id===owner)&&(type==='all'||r.customer_type===type)&&(level==='all'||r.level_id===level)&&(!q.trim()||[r.name,r.credit_code,r.industry,r.city,user(r.responsible_id),phone(r.id)].join(' ').toLowerCase().includes(q.trim().toLowerCase()))).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||''))),pageCount=Math.max(1,Math.ceil(filtered.length/20)),safePage=Math.min(page,pageCount),visible=filtered.slice((safePage-1)*20,safePage*20);
 function openCreate(){setDialog({name:'',customer_type:'company',category_id:state.categories[0]?.id||'',level_id:state.levels[0]?.id||'',responsible_id:current.id||state.users[0]?.id||'',credit_code:'',legal_representative:'',registered_capital:'',established_on:'',enterprise_scale:'',website:'',business_scope:'',industry:'',description:'',contact_name:'',job_title:'',gender:'',department:'',decision_weight:'',contact_remarks:'',mobile:'',landline:'',email:'',invoice_type:'',tax_number:'',bank_name:'',bank_account:'',invoice_address:'',invoice_phone:'',payment_term:'',revenue_recognition:'',credit_limit:'0',payment_days:'30',province:'',city:'',address:'',remarks:'',error:''})}
 function patch(key,value){setDialog(d=>({...d,[key]:value}))}
 async function save(){
  if(!dialog.name.trim()||!dialog.category_id||!dialog.responsible_id)return setDialog(d=>({...d,error:'请填写客户名称，并选择客户分类和主负责人'}));
  if((dialog.mobile||dialog.landline||dialog.email)&&!dialog.contact_name.trim())return setDialog(d=>({...d,error:'填写联系方式时必须填写联系人姓名'}));
  setBusy(true);
  try{
   const omit=['contact_name','job_title','gender','department','decision_weight','contact_remarks','mobile','landline','email','error'];
   const values=Object.fromEntries(Object.entries(dialog).filter(([key])=>!omit.includes(key)));
   const customer=await create('forge_customer',{...values,name:dialog.name.trim(),credit_limit:Number(dialog.credit_limit||0),payment_days:Number(dialog.payment_days||30),level_id:dialog.level_id||null,established_on:dialog.established_on||null});
   if(dialog.contact_name.trim()){
    const contact=await create('forge_contact',{name:dialog.contact_name.trim(),customer_id:customer.id,is_primary:true,job_title:dialog.job_title,gender:dialog.gender,department:dialog.department,decision_weight:dialog.decision_weight,remarks:dialog.contact_remarks});
    for(const item of [{channel_type:'mobile',name:'工作手机',value:dialog.mobile},{channel_type:'telephone',name:'办公座机',value:dialog.landline},{channel_type:'email',name:'工作邮箱',value:dialog.email}])if(item.value.trim())await create('forge_contact_channel',{...item,value:item.value.trim(),contact_id:contact.id});
   }
   setDialog(null);setToast(dialog.contact_name.trim()?'客户及主要联系人已创建':'客户已创建');setPage(1);await load();
  }catch(e){setDialog(d=>({...d,error:String(e.message||e)}))}finally{setBusy(false)}
 }
 const Section=({title,hint,children})=><section className="form-section"><div className="form-section-head"><div><div className="form-section-title">{title}</div>{hint&&<div className="form-section-hint">{hint}</div>}</div></div>{children}</section>;
 if(state.loading)return <div className="forge-product sales-customers"><style>{css}</style><div className="fp-shell"><ForgeLoading label="正在加载客户管理"/></div></div>;
 return <div className="forge-product sales-customers"><style>{css}</style><div className="fp-shell">
  <ForgePageHeader section="销售 / CRM客户管理" title="客户管理" description="按负责人范围管理客户档案、主要联系人、授信账期和经营跟进信息。" actions={<><button className="fp-button" onClick={load}>刷新</button><button className="fp-button primary" onClick={openCreate}>新增客户</button></>}/>
  {state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<ForgeNotice tone="success" onClose={()=>setToast('')}>{toast}</ForgeNotice>}
  <section className="fp-card">
   <div className="fp-tabs"><button className={'fp-tab '+(scope==='all'?'active':'')} onClick={()=>{setScope('all');setPage(1)}}>全部</button><button className={'fp-tab '+(scope==='mine'?'active':'')} onClick={()=>{setScope('mine');setPage(1)}}>我负责的</button><span className="fp-tab" aria-disabled="true">我参与的</span><span className="fp-tab" aria-disabled="true">下属负责的</span><span className="fp-tab" aria-disabled="true">下属参与的</span></div>
   <div className="scope-note">参与范围和下属范围依赖协同销售、团队成员及组织层级关系，RISEMAP 当前元素已保留；数据关系尚待同材料验证，因此不提供会产生误导的空筛选。</div>
   <div className="capability-strip"><span className="capability-chip">导入/导出 · 待任务能力复核</span><span className="capability-chip">批量操作 · 待动作规则复核</span><span className="capability-chip">扫描名片 · 待识别能力复核</span></div>
   <div className="fp-filterbar"><input className="fp-input fp-search" aria-label="搜索客户" placeholder="搜索客户名称、信用代码、行业或城市" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><ForgeSelectControl aria-label="分类" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="all">全部分类</option>{state.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl><ForgeSelectControl aria-label="主负责人" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}}><option value="all">全部负责人</option>{state.users.map(x=><option key={x.id} value={x.id}>{user(x.id)}</option>)}</ForgeSelectControl><ForgeSelectControl aria-label="客户类型" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">全部类型</option><option value="company">企业</option><option value="person">个人</option></ForgeSelectControl><ForgeSelectControl aria-label="级别" value={level} onChange={e=>{setLevel(e.target.value);setPage(1)}}><option value="all">全部级别</option>{state.levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl><button className="fp-button" onClick={()=>{setQ('');setCategory('all');setOwner('all');setType('all');setLevel('all');setScope('all');setPage(1)}}>重置筛选</button></div>
   <div className="capability-strip"><span className="capability-chip">协同销售筛选 · 待关系验证</span><span className="capability-chip">标签筛选 · 待字段验证</span><span className="capability-chip">状态筛选 · 待状态规则验证</span><span className="capability-chip">按创建时间降序</span></div>
   <div className="fp-table-wrap"><table className="fp-table"><thead><tr><th>客户名称</th><th>主负责人</th><th>主要联系人电话</th><th>协同销售</th><th>信用额度</th><th>账期天数</th><th>红绿灯</th><th>最近跟进时间</th><th>拜访计划日期</th><th>最近交易时间</th><th>操作</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="customer-name">{r.name}</div><div className="fp-secondary">{cat(r.category_id)} · {lvl(r.level_id)} · {r.customer_type==='person'?'个人':'企业'}</div></td><td>{user(r.responsible_id)}</td><td>{phone(r.id)}</td><td>—</td><td>{money(r.credit_limit)}</td><td>{Number(r.payment_days||0)} 天</td><td>—</td><td>{lastFollow(r.id)}</td><td>{nextVisit(r.id)}</td><td>{lastTrade(r.id)}</td><td><button className="fp-button small" onClick={()=>location.href='/_console/apps/forge/forge_customer/record/'+r.id}>查看</button></td></tr>)}{!visible.length&&<tr><td colSpan="11" className="fp-empty-cell"><ForgeEmpty title="暂无匹配客户" description="点击“新增客户”建立客户主档和主要联系人。" action={<button className="fp-button primary" onClick={openCreate}>新增客户</button>}/></td></tr>}</tbody></table></div>
   <div className="fp-pagination"><span>共 {filtered.length} 条记录</span><span>每页 20 条</span><button className="fp-button small" disabled={safePage<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>上一页</button><span>{safePage} / {pageCount}</span><button className="fp-button small" disabled={safePage>=pageCount} onClick={()=>setPage(value=>Math.min(pageCount,value+1))}>下一页</button></div>
  </section>
 </div>
 <ForgeDialog open={!!dialog} title="新增客户" subtitle="新增客户信息表单" error={dialog?.error} busy={busy} confirmLabel="创建客户" onCancel={()=>!busy&&setDialog(null)} onConfirm={save}>
  <Section title="企业查询" hint="RISEMAP 提供工商企业查询；Forge 尚未接入可信企业数据源，本区只说明能力，不提供假查询按钮。"><div className="fp-detail-grid"><div className="fp-field"><label>客户类型 *</label><ForgeSelectControl value={dialog?.customer_type||'company'} onChange={e=>patch('customer_type',e.target.value)}><option value="company">企业</option><option value="person">个人</option></ForgeSelectControl></div><div className="fp-field fp-span-2"><label>企业查询</label><div className="fp-secondary">待企业数据源与查询结果回填规则验证</div></div></div></Section>
  <Section title="工商信息 0/8"><div className="fp-detail-grid"><div className="fp-field fp-span-2"><label>客户名称 *</label><input className="fp-input" value={dialog?.name||''} onChange={e=>patch('name',e.target.value)}/></div><div className="fp-field"><label>统一社会信用代码</label><input className="fp-input" value={dialog?.credit_code||''} onChange={e=>patch('credit_code',e.target.value)}/></div><div className="fp-field"><label>法定代表人</label><input className="fp-input" value={dialog?.legal_representative||''} onChange={e=>patch('legal_representative',e.target.value)}/></div><div className="fp-field"><label>注册资金</label><input className="fp-input" value={dialog?.registered_capital||''} onChange={e=>patch('registered_capital',e.target.value)}/></div><div className="fp-field"><label>成立日期</label><ForgeDateInput value={dialog?.established_on||''} onChange={e=>patch('established_on',e.target.value)}/></div><div className="fp-field"><label>企业规模</label><input className="fp-input" value={dialog?.enterprise_scale||''} onChange={e=>patch('enterprise_scale',e.target.value)}/></div><div className="fp-field"><label>公司网站</label><input className="fp-input" value={dialog?.website||''} onChange={e=>patch('website',e.target.value)}/></div><div className="fp-field fp-span-2"><label>经营范围</label><textarea className="fp-textarea" value={dialog?.business_scope||''} onChange={e=>patch('business_scope',e.target.value)}/></div></div></Section>
  <Section title="联系人" hint="联系人独立维护，可随客户一次新增一位主要联系人；同一类型多条联系方式待联系人页复核。"><div className="fp-detail-grid"><div className="fp-field"><label>姓名</label><input className="fp-input" value={dialog?.contact_name||''} onChange={e=>patch('contact_name',e.target.value)}/></div><div className="fp-field"><label>职位</label><input className="fp-input" value={dialog?.job_title||''} onChange={e=>patch('job_title',e.target.value)}/></div><div className="fp-field"><label>性别</label><input className="fp-input" value={dialog?.gender||''} onChange={e=>patch('gender',e.target.value)}/></div><div className="fp-field"><label>部门</label><input className="fp-input" value={dialog?.department||''} onChange={e=>patch('department',e.target.value)}/></div><div className="fp-field"><label>决策权重</label><input className="fp-input" value={dialog?.decision_weight||''} onChange={e=>patch('decision_weight',e.target.value)}/></div><div className="fp-field"><label>备注</label><input className="fp-input" value={dialog?.contact_remarks||''} onChange={e=>patch('contact_remarks',e.target.value)}/></div><div className="fp-field"><label>手机 · 工作手机</label><input className="fp-input" value={dialog?.mobile||''} onChange={e=>patch('mobile',e.target.value)}/></div><div className="fp-field"><label>座机 · 办公座机</label><input className="fp-input" value={dialog?.landline||''} onChange={e=>patch('landline',e.target.value)}/></div><div className="fp-field"><label>邮箱 · 工作邮箱</label><input className="fp-input" value={dialog?.email||''} onChange={e=>patch('email',e.target.value)}/></div></div></Section>
  <Section title="客户资料 1/5"><div className="fp-detail-grid"><div className="fp-field"><label>客户分类 *</label><ForgeSelectControl value={dialog?.category_id||''} onChange={e=>patch('category_id',e.target.value)}><option value="">请选择分类</option>{state.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>客户级别</label><ForgeSelectControl value={dialog?.level_id||''} onChange={e=>patch('level_id',e.target.value)}><option value="">暂不设置</option>{state.levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>行业</label><input className="fp-input" value={dialog?.industry||''} onChange={e=>patch('industry',e.target.value)}/></div><div className="fp-field"><label>负责人 *</label><ForgeSelectControl value={dialog?.responsible_id||''} onChange={e=>patch('responsible_id',e.target.value)}>{state.users.map(x=><option key={x.id} value={x.id}>{user(x.id)}</option>)}</ForgeSelectControl></div><div className="fp-field fp-span-2"><label>客户描述</label><textarea className="fp-textarea" value={dialog?.description||''} onChange={e=>patch('description',e.target.value)}/></div></div></Section>
  <Section title="标签与团队" hint="RISEMAP 当前表单包含团队成员；标签与团队关系尚未在 Forge 建模，保留元素说明，不提供不可保存的控件。"><div className="fp-secondary">团队成员 · 待协同销售关系与权限规则验证</div></Section>
  <Section title="开票信息 0/6"><div className="fp-detail-grid"><div className="fp-field"><label>发票类型</label><input className="fp-input" value={dialog?.invoice_type||''} onChange={e=>patch('invoice_type',e.target.value)}/></div><div className="fp-field"><label>纳税人识别号</label><input className="fp-input" value={dialog?.tax_number||''} onChange={e=>patch('tax_number',e.target.value)}/></div><div className="fp-field"><label>开户银行</label><input className="fp-input" value={dialog?.bank_name||''} onChange={e=>patch('bank_name',e.target.value)}/></div><div className="fp-field"><label>银行账号</label><input className="fp-input" value={dialog?.bank_account||''} onChange={e=>patch('bank_account',e.target.value)}/></div><div className="fp-field"><label>开票地址</label><input className="fp-input" value={dialog?.invoice_address||''} onChange={e=>patch('invoice_address',e.target.value)}/></div><div className="fp-field"><label>开票电话</label><input className="fp-input" value={dialog?.invoice_phone||''} onChange={e=>patch('invoice_phone',e.target.value)}/></div></div></Section>
  <Section title="商务条件 0/2"><div className="fp-detail-grid"><div className="fp-field"><label>默认付款条件</label><input className="fp-input" value={dialog?.payment_term||''} onChange={e=>patch('payment_term',e.target.value)}/></div><div className="fp-field"><label>收入确认方式</label><input className="fp-input" value={dialog?.revenue_recognition||''} onChange={e=>patch('revenue_recognition',e.target.value)}/></div><div className="fp-field"><label>信用额度</label><input className="fp-input" inputMode="decimal" value={dialog?.credit_limit||''} onChange={e=>patch('credit_limit',e.target.value)}/></div><div className="fp-field"><label>账期天数</label><input className="fp-input" inputMode="numeric" value={dialog?.payment_days||''} onChange={e=>patch('payment_days',e.target.value)}/></div></div></Section>
  <Section title="商务信息 0/4"><div className="fp-detail-grid"><div className="fp-field"><label>省份</label><input className="fp-input" value={dialog?.province||''} onChange={e=>patch('province',e.target.value)}/></div><div className="fp-field"><label>城市</label><input className="fp-input" value={dialog?.city||''} onChange={e=>patch('city',e.target.value)}/></div><div className="fp-field fp-span-2"><label>详细地址</label><input className="fp-input" value={dialog?.address||''} onChange={e=>patch('address',e.target.value)}/></div><div className="fp-field fp-span-2"><label>备注</label><textarea className="fp-textarea" value={dialog?.remarks||''} onChange={e=>patch('remarks',e.target.value)}/></div></div></Section>
 </ForgeDialog>
 </div>
}
export default App;
${forgeProductUiRuntime}`;

export const SalesCustomersPage = {
  name: 'page_sales_customers',
  label: '客户管理',
  description: '按负责人范围管理客户档案、主要联系人、授信账期和经营跟进信息',
  icon: 'building-2',
  type: 'app' as const,
  kind: 'react' as const,
  source,
};
