import { Contact } from '../objects/customer.object.js';
import { contactProfileRuntime } from './contact-profile.page.js';
import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css = forgeProductUiCss + `
.sales-contacts .fp-shell{width:min(1500px,100%);padding-top:20px}.sales-contacts .fp-table{min-width:1160px}.sales-contacts .fp-metrics{grid-template-columns:repeat(4,minmax(0,1fr))}
.sales-contacts .contact-cell{display:flex;align-items:center;gap:10px}.sales-contacts .contact-avatar{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:var(--fp-soft);font-weight:700}
.sales-contacts .kp{display:inline-flex;margin-left:6px;padding:2px 6px;border-radius:999px;background:#fff1d6;color:#925d00;font-size:11px}.sales-contacts .channel{display:block;white-space:nowrap}
.sales-contacts.compact .fp-table th,.sales-contacts.compact .fp-table td{padding-top:7px;padding-bottom:7px}.sales-contacts .contact-filters{display:grid;grid-template-columns:minmax(280px,1.4fr) minmax(180px,.8fr) minmax(180px,.8fr) auto;gap:8px;align-items:center;padding:12px 16px}.sales-contacts .contact-filters>*{min-width:0}.sales-contacts .contact-filters .fp-input,.sales-contacts .contact-filters .fp-picker-trigger,.sales-contacts .contact-filters .fp-button{height:32px;min-height:32px}.sales-contacts .contact-filter-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;white-space:nowrap}.sales-contacts .transfer-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sales-contacts .transfer-actions .fp-button{justify-content:flex-start}
.sales-contacts .channel-row{display:grid;grid-template-columns:130px 1fr 1.4fr auto auto;gap:8px;align-items:end;margin-bottom:10px}.sales-contacts .channel-primary{color:var(--fp-warning);font-weight:650}
.sales-contacts .channel-row .fp-picker{min-width:0;width:100%}.sales-contacts .channel-row .fp-picker-trigger{width:100%}
.sales-contacts .fp-modal{width:min(900px,calc(100vw - 32px))}.sales-contacts .fp-modal-body{max-height:72vh;overflow:auto}.sales-contacts .form-section{margin-bottom:18px;padding:14px;border:1px solid var(--fp-line);border-radius:12px}.sales-contacts .form-title{font-weight:700;margin-bottom:12px}
@media(max-width:1200px){.sales-contacts .fp-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.sales-contacts .contact-filters{grid-template-columns:repeat(3,minmax(0,1fr))}.sales-contacts .contact-filters .fp-search{grid-column:1/-1}}
@media(max-width:760px){.sales-contacts .channel-row{grid-template-columns:1fr}.sales-contacts .fp-shell{padding-top:10px}.sales-contacts .contact-filters{grid-template-columns:1fr 1fr}.sales-contacts .contact-filters .fp-search,.sales-contacts .contact-filter-actions{grid-column:1/-1}.sales-contacts .contact-filter-actions{justify-content:flex-start}.sales-contacts .transfer-actions{grid-template-columns:1fr}}
@media(max-width:520px){.sales-contacts .fp-metrics,.sales-contacts .contact-filters{grid-template-columns:1fr}.sales-contacts .contact-filters .fp-search{grid-column:auto}}
`;

const source = `${contactProfileRuntime}

const css=${JSON.stringify(css)},statusText={active:'在职',transferred:'已跳槽',resigned:'已离职',retired:'已退休',inactive:'停用'},channelText={mobile:'手机',telephone:'座机',email:'邮箱',wechat:'微信',dingtalk:'钉钉',qq:'QQ',linkedin:'LinkedIn',other:'其他'},channelOptions=Object.entries(channelText),genderLabels=${JSON.stringify(Object.fromEntries((Contact.fields.gender.options ?? []).map(option=>[option.value,option.label])))},weightLabels=${JSON.stringify(Object.fromEntries((Contact.fields.decision_weight.options ?? []).map(option=>[option.value,option.label])))};
function App(){
 const adapter=useAdapter();
 const [state,setState]=React.useState({loading:true,currentUserId:'',contacts:[],channels:[],customers:[],users:[],error:''}),[tab,setTab]=React.useState('all'),[q,setQ]=React.useState(''),[job,setJob]=React.useState(''),[owner,setOwner]=React.useState('all'),[compact,setCompact]=React.useState(false),[page,setPage]=React.useState(1),[dialog,setDialog]=React.useState(null),[transferOpen,setTransferOpen]=React.useState(false),[busy,setBusy]=React.useState(false),[toast,setToast]=React.useState('');
 async function request(path,options={}){const headers={'Content-Type':'application/json',...(adapter?.getAuthHeaders?.()||{}),...(options.headers||{})},raw=String(adapter?.baseUrl||''),base=raw.endsWith('/')?raw.slice(0,-1):raw,transport=adapter?.fetchImpl||fetch,response=await transport(base+'/api/v1'+path,{credentials:'include',...options,headers}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error((typeof payload.error==='string'?payload.error:payload.error?.message)||(Array.isArray(payload.fields)&&payload.fields.length?payload.fields.map(f=>f.message||f.label).filter(Boolean).join('；'):'')||payload.message||'请求失败');return payload}
 const rows=p=>p?.records||p?.data?.records||p?.data||[],result=p=>p?.record||p?.data?.record||p?.data||p;
 async function find(name){return rows(await request('/data/'+name+'?$top=500'))}
 async function load(){setState(s=>({...s,loading:true,error:''}));try{const [session,contacts,channels,customers,users]=await Promise.all([request('/auth/get-session'),...['forge_contact','forge_contact_channel','forge_customer','sys_user'].map(find)]);const currentUserId=session.user?.id||session.session?.user?.id;if(!currentUserId)throw new Error('登录已失效，请重新登录');setState({loading:false,currentUserId,contacts,channels,customers,users,error:''})}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}))}}
 React.useEffect(()=>{load()},[]);
 const customer=id=>state.customers.find(x=>x.id===id)?.name||'—',user=id=>{const r=state.users.find(x=>x.id===id);return r?.name||r?.display_name||r?.email||'—'},current=state.users.find(x=>x.id===state.currentUserId)||{id:state.currentUserId},channelsOf=id=>state.channels.filter(x=>x.contact_id===id),isKp=r=>Object.keys(weightLabels).includes(r.decision_weight)||Object.values(weightLabels).includes(r.decision_weight),status=r=>r.employment_status||'active';
 const counts={all:state.contacts.length,active:state.contacts.filter(x=>status(x)==='active').length,transferred:state.contacts.filter(x=>status(x)==='transferred').length,resigned:state.contacts.filter(x=>status(x)==='resigned').length,retired:state.contacts.filter(x=>status(x)==='retired').length,inactive:state.contacts.filter(x=>status(x)==='inactive').length},filtered=state.contacts.filter(r=>(tab==='all'||status(r)===tab)&&(owner==='all'||r.responsible_id===owner)&&(!job.trim()||[r.job_title,r.department].join(' ').toLowerCase().includes(job.trim().toLowerCase()))&&(!q.trim()||[r.name,customer(r.customer_id),r.job_title,r.department,...channelsOf(r.id).map(x=>x.value)].join(' ').toLowerCase().includes(q.trim().toLowerCase()))).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||''))),pageCount=Math.max(1,Math.ceil(filtered.length/20)),safePage=Math.min(page,pageCount),visible=filtered.slice((safePage-1)*20,safePage*20);
 function openCreate(){setDialog({kind:'edit',row:null})}
 function openEdit(row){setDialog({kind:'edit',row})}
 async function remove(){const row=dialog.row;setBusy(true);try{for(const x of channelsOf(row.id))await request('/data/forge_contact_channel/'+x.id,{method:'DELETE'});await request('/data/forge_contact/'+row.id,{method:'DELETE'});setDialog(null);setToast('联系人已删除');await load()}catch(e){setDialog(d=>({...d,error:String(e.message||e)}))}finally{setBusy(false)}}
 function exportCsv(mode){const exportRows=mode==='page'?visible:filtered,headers=['联系人','性别','职位','部门','所属公司','任职状态','决策权重','联系方式','维护人'],quote=String.fromCharCode(34),newline=String.fromCharCode(10),csv=[headers,...exportRows.map(r=>[r.name,r.gender||'',r.job_title||'',r.department||'',customer(r.customer_id),statusText[status(r)]||status(r),r.decision_weight||'',channelsOf(r.id).map(x=>x.name+'：'+x.value).join('；'),user(r.responsible_id)])].map(line=>line.map(value=>quote+String(value??'').split(quote).join(quote+quote)+quote).join(',')).join(newline),url=URL.createObjectURL(new Blob([String.fromCharCode(65279)+csv],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download='联系人管理-'+new Date().toISOString().slice(0,10)+'.csv';anchor.click();URL.revokeObjectURL(url);setTransferOpen(false);setToast('已导出 '+exportRows.length+' 条联系人记录')}
 if(state.loading)return <div className="forge-product sales-contacts"><style>{css}</style><div className="fp-shell"><ForgeLoading label="正在加载联系人管理"/></div></div>;
 return <div className={'forge-product sales-contacts '+(compact?'compact':'')}><style>{css}</style><div className="fp-shell"><ForgePageHeader section="CRM客户管理 / 联系人管理" title="联系人管理"  actions={<><button className="fp-button primary" onClick={openCreate}>＋ 新增联系人</button><button className="fp-button" onClick={()=>setTransferOpen(true)}>⇅ 导入/导出⌄</button></>}/>{state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<ForgeNotice tone="success" onClose={()=>setToast('')}>{toast}</ForgeNotice>}
 <div className="fp-metrics"><div className="fp-metric"><div className="fp-metric-label">联系人总数</div><div className="fp-metric-value">{counts.all}</div></div><div className="fp-metric"><div className="fp-metric-label">在职</div><div className="fp-metric-value">{counts.active}</div></div><div className="fp-metric"><div className="fp-metric-label">不在原公司</div><div className="fp-metric-value">{counts.transferred+counts.resigned+counts.retired}</div></div><div className="fp-metric"><div className="fp-metric-label">关键决策人 KP</div><div className="fp-metric-value">{state.contacts.filter(isKp).length}</div></div></div>
 <section className="fp-card"><div className="fp-tabs">{[['all','全部'],['active','在职'],['transferred','已跳槽'],['resigned','已离职'],['retired','已退休'],['inactive','停用']].map(([v,l])=><button key={v} className={'fp-tab '+(tab===v?'active':'')} onClick={()=>{setTab(v);setPage(1)}}>{l} {counts[v]}</button>)}</div><div className="contact-filters"><input className="fp-input fp-search" aria-label="搜索联系人" placeholder="搜索姓名、公司、电话、邮箱" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><input className="fp-input" aria-label="按职务筛选联系人" placeholder="筛选职务" value={job} onChange={e=>{setJob(e.target.value);setPage(1)}}/><ForgeSelectControl aria-label="维护人" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}}><option value="all">全部维护人</option>{state.users.map(x=><option value={x.id} key={x.id}>{user(x.id)}</option>)}</ForgeSelectControl><div className="contact-filter-actions"><button className="fp-button" onClick={()=>{setQ('');setJob('');setOwner('all');setPage(1)}}>清空筛选</button><button className="fp-icon-button" aria-label="刷新联系人数据" title="刷新联系人数据" onClick={load}>↻</button><button className="fp-icon-button" aria-label={compact?'切换为标准行高':'切换为紧凑行高'} title={compact?'切换为标准行高':'切换为紧凑行高'} onClick={()=>setCompact(value=>!value)}>≡</button><ForgeListSettings/></div></div>
 <div className="fp-table-wrap"><table className="fp-table"><thead><tr><th>联系人</th><th>性别</th><th>职位 / 部门</th><th>所属公司</th><th>任职状态</th><th>决策权重</th><th>联系方式</th><th>维护人</th><th>操作</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="contact-cell"><span className="contact-avatar">{String(r.name||'联').slice(0,1)}</span><div><strong>{r.name}</strong>{isKp(r)&&<span className="kp">KP</span>}{r.is_primary&&<div className="fp-secondary">主要联系人</div>}</div></div></td><td>{genderLabels[r.gender]||r.gender||'—'}</td><td>{r.job_title||'—'}<div className="fp-secondary">{r.department||'—'}</div></td><td>{customer(r.customer_id)}</td><td><ForgeStatus value={status(r)} label={statusText[status(r)]}/></td><td>{weightLabels[r.decision_weight]||r.decision_weight||'—'}</td><td>{channelsOf(r.id).map(x=><span className="channel" key={x.id}>{x.is_primary?'★ ':''}{x.value}</span>)}{!channelsOf(r.id).length&&'—'}</td><td>{user(r.responsible_id)}</td><td><div className="fp-toolbar"><button className="fp-button small" onClick={()=>openEdit(r)}>编辑</button><button className="fp-button small danger" onClick={()=>setDialog({kind:'delete',row:r,error:''})}>删除</button></div></td></tr>)}{!visible.length&&<tr><td colSpan="9" className="fp-empty-cell"><ForgeEmpty title="暂无联系人" description="新增联系人后，可按任职状态、职务和维护人持续管理。" action={<button className="fp-button primary" onClick={openCreate}>新增联系人</button>}/></td></tr>}</tbody></table></div><div className="fp-pagination"><span>共 {filtered.length} 条记录</span><span>每页 20 条</span><button className="fp-button small" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>上一页</button><span>{safePage} / {pageCount}</span><button className="fp-button small" disabled={safePage>=pageCount} onClick={()=>setPage(x=>Math.min(pageCount,x+1))}>下一页</button></div></section></div>
 {dialog?.kind==='edit'&&<ContactProfileEditor key={dialog.row?.id||'new'} row={dialog.row} channels={dialog.row?channelsOf(dialog.row.id):[]} currentUserId={state.currentUserId} customers={state.customers} users={state.users} onClose={()=>setDialog(null)} onSaved={async()=>{setDialog(null);setToast('联系人已保存');await load()}}/>}
 <ForgeDialog open={dialog?.kind==='delete'} title="确认删除联系人" subtitle={dialog?.row?.name} error={dialog?.error} busy={busy} danger confirmLabel="确认删除" onCancel={()=>!busy&&setDialog(null)} onConfirm={remove}><div className="fp-dialog-impact">删除后将同时移除该联系人的全部联系方式，且无法恢复；所属客户档案不会被删除。</div></ForgeDialog>
 <ForgeDialog open={transferOpen} title="导入 / 导出联系人" subtitle="联系人档案的数据交换" confirmLabel="关闭" onCancel={()=>setTransferOpen(false)} onConfirm={()=>setTransferOpen(false)}><div className="transfer-actions"><button className="fp-button" onClick={()=>location.href='/_console/apps/com.inoforge.forge.sales/forge_contact'}>批量导入 · 前往联系人台账</button><button className="fp-button" disabled={!visible.length} onClick={()=>exportCsv('page')}>导出当前页</button><button className="fp-button" disabled={!filtered.length} onClick={()=>exportCsv('all')}>导出全部筛选结果</button></div><ForgeNotice tone="info">自定义导出与批量任务尚未形成可回读的任务中心，不显示为可点击动作。</ForgeNotice></ForgeDialog>
 </div>}
export default App;${forgeProductUiRuntime}`;

export const SalesContactsPage={name:'page_sales_contacts',label:'联系人管理',description:'以人为中心管理客户联系人，持续跟踪任职变化和全部联系方式',icon:'contact',type:'app' as const,kind:'react' as const,source};
