import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const source = `
function App(){
 const [state,setState]=React.useState({loading:true,error:'',suppliers:[],orders:[],receipts:[],lines:[],reconciliations:[],payables:[]}),[query,setQuery]=React.useState(''),[supplierId,setSupplierId]=React.useState('all'),[statusFilter,setStatusFilter]=React.useState('all'),[start,setStart]=React.useState(''),[end,setEnd]=React.useState('');
 async function request(path){const r=await fetch('/api/v1'+path,{credentials:'include'}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error?.message||p.message||'请求失败');return p;}
 async function find(name){return(await request('/data/'+name+'?$top=500')).records||[];}
 async function load(){try{const names=['forge_supplier','forge_subcontract_order','forge_subcontract_receipt','forge_subcontract_reconciliation','forge_subcontract_reconciliation_line','forge_accounts_payable'],rows=await Promise.all(names.map(find));setState({loading:false,error:'',suppliers:rows[0],orders:rows[1],receipts:rows[2],reconciliations:rows[3],lines:rows[4],payables:rows[5]});}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}));}}
 React.useEffect(()=>{load();},[]);
 const money=v=>'¥'+Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),status={pending_confirmation:'待确认',confirmed:'已确认',payable_generated:'已生成应付',voided:'已作废'},supplierMap=Object.fromEntries(state.suppliers.map(x=>[x.id,x])),orderMap=Object.fromEntries(state.orders.map(x=>[x.id,x])),payableMap=Object.fromEntries(state.payables.map(x=>[x.id,x]));
 const visible=state.reconciliations.filter(x=>{const supplier=supplierMap[x.supplier_id],hay=[x.code,payableMap[x.payable_id]?.code,...state.lines.filter(line=>line.reconciliation_id===x.id).map(line=>orderMap[line.order_id]?.code)].filter(Boolean).join(' ').toLowerCase(),needle=query.trim().toLowerCase();return(supplierId==='all'||x.supplier_id===supplierId)&&(statusFilter==='all'||x.status===statusFilter)&&(!start||String(x.period_end||'')>=start)&&(!end||String(x.period_start||'')<=end)&&(!needle||hay.includes(needle));});
 function exportCsv(){const head=['对账单号','供应商','账期开始','账期结束','行数','加工费','补料','扣款','应付','关联应付','状态'],body=visible.map(x=>[x.code,supplierMap[x.supplier_id]?.name||x.supplier_id,x.period_start,x.period_end,x.line_count,x.processing_amount,x.replenishment_amount,x.deduction_amount,x.payable_amount,payableMap[x.payable_id]?.code||'',status[x.status]||x.status]);const csv=[head,...body].map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\\n'),blob=new Blob(['\\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='委外对账单.csv';a.click();URL.revokeObjectURL(url);}
 const css=${JSON.stringify(forgeProductUiCss + '.fsrr{min-height:100%;background:#f4f6f8;color:#222831}.fsrr .head{padding:18px 22px;background:#fff;border-bottom:1px solid #e1e5ea}.fsrr .head h1{margin:0 0 5px;font-size:22px}.fsrr .head p{margin:0;color:#76808d;font-size:12px}.fsrr .body{padding:18px 22px 40px;max-width:1480px;margin:auto}.fsrr .toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin-bottom:14px}.fsrr .field{display:flex;flex-direction:column;gap:5px;min-width:170px}.fsrr .field input{border:1px solid #ccd3da;border-radius:4px;padding:8px}.fsrr .btn{height:34px;border:1px solid #ccd3da;border-radius:4px;background:#fff;padding:0 11px}.fsrr .primary{background:#1769e0;color:#fff;border-color:#1769e0}.fsrr .notice{padding:10px 13px;background:#fff3cd;color:#745600;border-radius:5px;margin-bottom:14px}.fsrr .table{overflow:auto;border:1px solid #e1e5ea;border-radius:5px;background:#fff}.fsrr table{width:100%;border-collapse:collapse;font-size:12px;min-width:1250px}.fsrr th,.fsrr td{padding:9px 10px;border-bottom:1px solid #edf0f3;text-align:left;vertical-align:top}.fsrr th{background:#f7f8fa;color:#68727f;font-weight:500}.fsrr .pill{font-size:11px;padding:3px 8px;border-radius:10px;background:#edf4ff;color:#1769e0}.fsrr .warn{background:#fff1e8;color:#a14b00}.fsrr .muted{font-size:12px;color:#76808d}.fsrr .source{padding:9px 10px;background:#f7f9fb}.fsrr .empty{padding:28px;text-align:center;color:#76808d}.fsrr .summary{display:flex;gap:24px;padding:12px 2px;color:#596574;font-size:12px}@media(max-width:900px){.fsrr .body{padding:10px}.fsrr .toolbar{align-items:stretch}.fsrr .field{min-width:145px}}')};
 if(state.loading)return <div className="forge-product fsrr"><style>{css}</style><div className="body">正在加载委外对账单…</div></div>;
 const total=visible.reduce((s,x)=>s+Number(x.payable_amount||0),0);
 return <div className="forge-product fsrr"><style>{css}</style><div className="head"><h1>委外对账单</h1><p>集中查看委外加工费、补料、扣款、应付和来源订单</p></div><div className="body">{state.error&&<div className="notice">{state.error}</div>}<div className="toolbar"><div className="field"><label>搜索对账单号 / 应付单号 / 关联订单号</label><input aria-label="搜索委外对账单" placeholder="输入单号后筛选" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="field"><label>供应商</label><ForgeSelectControl aria-label="委外对账单供应商" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="all">全部供应商</option>{state.suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div><div className="field"><label>状态</label><ForgeSelectControl aria-label="委外对账单状态" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option><option value="pending_confirmation">待确认</option><option value="confirmed">已确认</option><option value="payable_generated">已生成应付</option><option value="voided">已作废</option></ForgeSelectControl></div><div className="field"><label>开始日期</label><ForgeDateInput aria-label="委外对账单开始日期" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>结束日期</label><ForgeDateInput aria-label="委外对账单结束日期" value={end} onChange={e=>setEnd(e.target.value)}/></div><button className="btn" aria-label="刷新委外对账单" onClick={load}>刷新</button><button className="btn" aria-label="导出委外对账单" onClick={exportCsv}>导出</button></div><div className="summary"><span>共 {visible.length} 张对账单</span><span>当前应付合计 {money(total)}</span><span>状态筛选：{statusFilter==='all'?'全部':status[statusFilter]}</span></div><div className="table"><table><thead><tr><th>对账单号</th><th>供应商</th><th>账期</th><th>行数</th><th>加工费</th><th>补料</th><th>扣款</th><th>应付</th><th>关联应付</th><th>状态</th></tr></thead><tbody>{visible.map(x=><React.Fragment key={x.id}><tr><td>{x.code}</td><td>{supplierMap[x.supplier_id]?.name||x.supplier_id}</td><td>{x.period_start} 至 {x.period_end}</td><td>{x.line_count}</td><td>{money(x.processing_amount)}</td><td>{money(x.replenishment_amount)}</td><td>{money(x.deduction_amount)}</td><td>{money(x.payable_amount)}</td><td>{x.payable_id?(payableMap[x.payable_id]?.code||x.payable_id):'—'}</td><td><span className={'pill '+(x.status==='voided'?'warn':'')}>{status[x.status]||x.status}</span></td></tr><tr><td colSpan="10" className="source">来源：{state.lines.filter(line=>line.reconciliation_id===x.id).map(line=><span key={line.id} style={{marginRight:16}}>{orderMap[line.order_id]?.code||line.order_id} / {line.receipt_id} / {money(line.amount)}</span>)}</td></tr></React.Fragment>)}{!visible.length&&<tr><td colSpan="10" className="empty">暂无符合条件的委外对账单</td></tr>}</tbody></table></div></div></div>;
}
${forgeProductUiRuntime}
`;

export const SubcontractReconciliationReportPage = { name: 'page_subcontract_reconciliation_report', label: '委外对账单', description: '委外对账结果、费用构成和关联应付报表', icon: 'file-chart-column', type: 'app' as const, kind: 'react' as const, source };
