import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css =
  forgeProductUiCss +
  `.forge-warehouses .fp-shell{max-width:1600px}.forge-warehouses .fp-table{min-width:1040px}.forge-warehouses .fp-table th,.forge-warehouses .fp-table td{padding-left:10px;padding-right:10px}.forge-warehouses .fp-filterbar{grid-template-columns:minmax(280px,1fr) 200px}`;

const source = `
${forgeProductUiRuntime}
const css=${JSON.stringify(css)};
function App(){
  const [state,setState]=React.useState({loading:true,warehouses:[],types:[],users:[],balances:[],orders:[],error:''}),[query,setQuery]=React.useState(''),[type,setType]=React.useState(''),[page,setPage]=React.useState(1),[dialog,setDialog]=React.useState(null),[busy,setBusy]=React.useState(false),[toast,setToast]=React.useState('');
  async function request(path,options={}){const r=await fetch('/api/v1'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error&&p.error.message||p.message||('HTTP '+r.status));return p;}
  async function load(){setState(s=>({...s,loading:true,error:''}));try{const [warehouses,types,users,balances,orders]=await Promise.all(['forge_warehouse','forge_warehouse_type','sys_user','forge_inventory_balance','forge_purchase_order'].map(n=>request('/data/'+n+'?$top=500').then(p=>p.records||[]).catch(()=>[])));setState({loading:false,warehouses,types,users,balances,orders,error:''});}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}));}}
  React.useEffect(()=>{load()},[]);
  const byId=(rows,id)=>rows.find(x=>x.id===id),typeName=id=>byId(state.types,id)?.name||'—',userName=id=>{const u=byId(state.users,id);return u?.display_name||u?.name||'—'};
  const totalSku=new Set(state.balances.map(b=>b.sku_id).filter(Boolean)).size,totalOnhand=state.balances.reduce((sum,b)=>sum+Number(b.on_hand_quantity||0),0),totalPurchase=state.orders.reduce((sum,o)=>sum+Number(o.total_amount||0),0);
  const filtered=state.warehouses.filter(w=>(!query||[w.code,w.name,w.address,w.phone].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))&&(!type||w.type_id===type));
  const pageSize=20,total=filtered.length,pages=Math.max(1,Math.ceil(total/pageSize)),safePage=Math.min(page,pages),rows=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  function defaults(){return{id:'',code:'WH-'+Date.now(),name:'',type_id:'',responsible_id:'',phone:'',area:'',address:'',error:''}}
  function openNew(){setDialog({kind:'form',form:defaults()})}
  function openEdit(row){setDialog({kind:'form',form:{id:row.id,code:row.code||'',name:row.name||'',type_id:row.type_id||'',responsible_id:row.responsible_id||'',phone:row.phone||'',area:row.area==null?'':String(row.area),address:row.address||'',error:''}})}
  async function save(){const f=dialog.form;const fail=msg=>setDialog(d=>({...d,form:{...d.form,error:msg}}));if(!f.name.trim())return fail('请填写仓库名称');if(!f.type_id)return fail('请选择仓库类型');if(!f.phone.trim())return fail('请填写联系电话');if(!f.area||!(Number(f.area)>0))return fail('请填写大于 0 的仓库面积');if(!f.address.trim())return fail('请填写仓库地址');if(state.warehouses.some(w=>w.code===f.code.trim()&&w.id!==f.id))return fail('仓库编码已存在');setBusy(true);try{const body={name:f.name.trim(),code:f.code.trim()||null,type_id:f.type_id,responsible_id:f.responsible_id||null,phone:f.phone.trim(),area:Number(f.area),address:f.address.trim()};await request('/data/forge_warehouse'+(f.id?'/'+f.id:''),{method:f.id?'PATCH':'POST',body:JSON.stringify(body)});setDialog(null);setToast(f.id?'仓库已更新':'仓库已创建');await load();}catch(e){fail(String(e.message||e));}finally{setBusy(false)}}
  function askDelete(row){setDialog({kind:'delete',row,error:'',impact:'删除后该仓库档案不可恢复；若仓库已有库存、单据或物料默认仓库引用，请先转移后再删除。'})}
  async function remove(){const d=dialog;setBusy(true);try{await request('/data/forge_warehouse/'+d.row.id,{method:'DELETE'});setDialog(null);setToast('仓库已删除');await load();}catch(e){setDialog(x=>({...x,error:String(e.message||e)+'；如该仓库已被库存或单据引用，请先转移业务数据。'}));}finally{setBusy(false)}}
  function exportCsv(){const head=['仓库编码','仓库名称','仓库类型','负责人','联系电话','面积（㎡）','仓库地址'],body=filtered.map(w=>[w.code,w.name,typeName(w.type_id),userName(w.responsible_id),w.phone,w.area,w.address]),csv=[head,...body].map(r=>r.map(v=>'"'+String(v==null?'':v).replace(/"/g,'""')+'"').join(',')).join('\\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\\ufeff'+csv],{type:'text/csv'}));a.download='仓库档案.csv';a.click();setToast('已导出 '+body.length+' 个仓库');}
  if(state.loading)return <div className="forge-product forge-warehouses"><style>{css}</style><ForgeLoading label="正在加载仓库管理"/></div>;
  const form=dialog&&dialog.kind==='form'?dialog.form:null;
  return <div className="forge-product forge-warehouses"><style>{css}</style><div className="fp-shell"><ForgeHero section="供应链 / 基础资料 / 仓库管理" title="仓库管理" description="管理主仓 / 项目仓 / 备品仓，掌握库存、采购、销售全景" icon="▤" tone="slate" art="boxes"/><ForgeMetricStrip items={[{label:'总仓库数',value:total,icon:'box'},{label:'库存 SKU',value:totalSku,icon:'gauge'},{label:'库存总量',value:Number(totalOnhand.toFixed(4)),icon:'box'},{label:'总采购金额',value:'¥'+Number(totalPurchase.toFixed(2)).toLocaleString('zh-CN'),icon:'money'}]}/>{state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<ForgeNotice tone="success" onClose={()=>setToast('')}>{toast}</ForgeNotice>}
    <div className="fp-action-row"><button className="fp-button primary" onClick={openNew}>新增仓库</button><button className="fp-button" disabled={!filtered.length} onClick={exportCsv}>导出</button><button className="fp-button" onClick={()=>setDialog({kind:'note',title:'导入/导出任务',text:'仓库导入使用平台导入能力：可在列表右上角「导入」按模板批量新增仓库。本页导出按钮按当前筛选结果导出 CSV。'})}>导入/导出</button><span className="fp-action-end"><button className="fp-icon-button" aria-label="刷新" title="刷新" onClick={load}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7"/><path d="M21 3v6h-6"/></svg></button></span></div>
    <section className="fp-card"><div className="fp-filterbar"><input className="fp-input fp-search" aria-label="搜索仓库" placeholder="搜索仓库名称、仓库编码、仓库地址" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><ForgeSelectControl aria-label="仓库类型" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">全部仓库类型</option>{state.types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</ForgeSelectControl></div><div className="fp-table-wrap"><table className="fp-table"><thead><tr><th>仓库编码</th><th>仓库名称</th><th>仓库类型</th><th>负责人</th><th>联系电话</th><th>面积（㎡）</th><th>仓库地址</th><th>操作</th></tr></thead><tbody>{rows.map(w=><tr key={w.id}><td><strong>{w.code||'—'}</strong></td><td>{w.name}</td><td>{typeName(w.type_id)}</td><td>{userName(w.responsible_id)}</td><td>{w.phone||'—'}</td><td>{w.area==null?'—':Number(w.area).toLocaleString('zh-CN')}</td><td>{w.address||'—'}</td><td><button className="fp-link-button" onClick={()=>openEdit(w)}>编辑</button><button className="fp-link-button" onClick={()=>askDelete(w)}>删除</button></td></tr>)}{!rows.length&&<tr><td colSpan="8" className="fp-empty-cell"><ForgeEmpty title="暂无匹配的仓库" description="调整筛选条件，或点击“新增仓库”维护仓库档案。" action={<button className="fp-button primary" onClick={openNew}>新增仓库</button>}/></td></tr>}</tbody></table></div><div className="fp-pagination"><span>共 {total} 条记录 · 每页 {pageSize} 条</span><span><button className="fp-button" disabled={safePage<=1} onClick={()=>setPage(safePage-1)}>上一页</button><span className="fp-secondary" style={{margin:'0 8px'}}>{safePage} / {pages}</span><button className="fp-button" disabled={safePage>=pages} onClick={()=>setPage(safePage+1)}>下一页</button></span></div></section>
    <ForgeDialog open={!!form} title={form&&form.id?'编辑仓库':'新增仓库'} subtitle="仓库决定入库、库存与出库的业务范围" error={form&&form.error} busy={busy} confirmLabel={form&&form.id?'保存修改':'创建仓库'} onCancel={()=>!busy&&setDialog(null)} onConfirm={save}><div className="fp-form-grid"><div className="fp-field"><label>仓库编码</label><input className="fp-input" aria-label="仓库编码" value={form&&form.code||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,code:e.target.value,error:''}}))}/></div><div className="fp-field"><label>仓库名称 *</label><input className="fp-input" aria-label="仓库名称" value={form&&form.name||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,name:e.target.value,error:''}}))}/></div><div className="fp-field"><label>仓库类型 *</label><ForgeSelectControl aria-label="仓库类型选择" value={form&&form.type_id||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,type_id:e.target.value,error:''}}))}><option value="">请选择仓库类型</option>{state.types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>负责人</label><ForgeSelectControl aria-label="仓库负责人" value={form&&form.responsible_id||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,responsible_id:e.target.value}}))}><option value="">请选择负责人</option>{state.users.map(u=><option key={u.id} value={u.id}>{u.display_name||u.name}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>联系电话 *</label><input className="fp-input" aria-label="仓库联系电话" value={form&&form.phone||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,phone:e.target.value,error:''}}))}/></div><div className="fp-field"><label>面积（㎡）*</label><input className="fp-input" type="number" min="0" aria-label="仓库面积" value={form&&form.area||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,area:e.target.value,error:''}}))}/></div><div className="fp-field"><label>仓库地址 *</label><input className="fp-input" aria-label="仓库地址" value={form&&form.address||''} onChange={e=>setDialog(d=>({...d,form:{...d.form,address:e.target.value,error:''}}))}/></div></div></ForgeDialog>
    <ForgeDialog open={dialog&&dialog.kind==='delete'} title="删除仓库" subtitle={dialog&&dialog.row?dialog.row.code+' · '+dialog.row.name:''} error={dialog&&dialog.error} busy={busy} danger confirmLabel="确认删除" onCancel={()=>!busy&&setDialog(null)} onConfirm={remove}><div className="fp-dialog-impact">{dialog&&dialog.impact}</div></ForgeDialog>
    <ForgeDialog open={dialog&&dialog.kind==='note'} title={dialog&&dialog.title} confirmLabel="知道了" onCancel={()=>setDialog(null)} onConfirm={()=>setDialog(null)}><div className="fp-dialog-impact">{dialog&&dialog.text}</div></ForgeDialog>
  </div></div>;
}
export default App;
`;

export const WarehouseWorkspacePage = {
  name: 'page_warehouse_workspace',
  label: '仓库管理',
  description: '管理主仓 / 项目仓 / 备品仓，掌握库存、采购、销售全景',
  icon: 'warehouse',
  type: 'app' as const,
  kind: 'react' as const,
  source,
};
