import { Field } from '@objectstack/spec/data';
import { master, text, code, reference, owner, remarks, required } from '../model.js';

const quantity = (label: string, mandatory = false, defaultValue?: number) => Field.number({
  label, min: 0, scale: 4, ...(mandatory ? required : {}), ...(defaultValue === undefined ? {} : { defaultValue }),
});
const nonNegativeMoney = (label: string) => Field.currency({ label, precision: 18, scale: 4, min: 0 });
const inboundStatus = () => Field.select([
  { value: 'draft', label: '草稿' },
  { value: 'pending_approval', label: '待审批' },
  { value: 'stocked', label: '已入库' },
  { value: 'rejected', label: '已驳回' },
], { label: '入库状态', defaultValue: 'draft', readonly: true });

// RM-028 runtime evidence. Header and lines remain separate so approval can audit
// the exact quantity and value that produced each balance movement.
export const OpeningInbound = master('forge_opening_inbound', '期初入库单', 'package-plus', {
  name: text('入库单名称', true), code: code('入库单号'), inbound_on: Field.date({ label: '入库日期', ...required }),
  warehouse_id: reference('forge_warehouse', '入库仓库', true), line_count: quantity('物料行数', false, 0),
  total_quantity: quantity('入库数量', false, 0), total_amount: nonNegativeMoney('含税金额'),
  status: inboundStatus(), responsible_id: owner(true), approval_note: Field.textarea({ label: '审批意见', readonly: true }),
  approved_at: Field.datetime({ label: '审批时间', readonly: true }), remarks: remarks(),
}, ['code', 'name', 'warehouse_id', 'inbound_on', 'line_count', 'total_quantity', 'total_amount', 'status', 'responsible_id']);

export const OpeningInboundLine = master('forge_opening_inbound_line', '期初入库明细', 'list', {
  name: text('物料名称', true), inbound_id: reference('forge_opening_inbound', '期初入库单', true),
  sku_id: reference('forge_material_sku', '物料规格', true), item_code: text('物料编码'), model: text('型号'),
  specification: text('规格'), unit_name: text('单位'), quantity: quantity('入库数量', true),
  taxed_unit_price: nonNegativeMoney('含税单价'), untaxed_unit_price: nonNegativeMoney('不含税单价'),
  tax_rate: Field.number({ label: '税率', min: 0, max: 100, scale: 4, defaultValue: 13 }),
  tax_amount: nonNegativeMoney('税额'), taxed_amount: nonNegativeMoney('含税金额'), remarks: remarks(),
}, ['inbound_id', 'item_code', 'name', 'model', 'quantity', 'taxed_unit_price', 'taxed_amount']);

// One current balance per warehouse and SKU. balance_key is generated by the
// approval action and enforces that invariant at storage level.
export const InventoryBalance = master('forge_inventory_balance', '库存余额', 'boxes', {
  name: text('库存名称', true), balance_key: code('余额键'), warehouse_id: reference('forge_warehouse', '仓库', true),
  sku_id: reference('forge_material_sku', '物料规格', true), on_hand_quantity: { ...quantity('当前库存', false, 0), readonly: true },
  reserved_quantity: { ...quantity('占用数量', false, 0), readonly: true },
  available_quantity: { ...quantity('可用库存', false, 0), readonly: true },
  average_cost: { ...nonNegativeMoney('移动平均含税成本'), readonly: true },
  inventory_value: { ...nonNegativeMoney('库存含税金额'), readonly: true },
  last_movement_at: Field.datetime({ label: '最近变动时间', readonly: true }), remarks: remarks(),
}, ['warehouse_id', 'sku_id', 'on_hand_quantity', 'reserved_quantity', 'available_quantity', 'average_cost', 'inventory_value', 'last_movement_at']);

export const InventoryLedger = master('forge_inventory_ledger', '库存流水', 'book-open', {
  name: text('流水名称', true), code: code('流水号'), warehouse_id: reference('forge_warehouse', '仓库', true),
  sku_id: reference('forge_material_sku', '物料规格', true), direction: Field.select([
    { value: 'inbound', label: '入库' }, { value: 'outbound', label: '出库' },
  ], { label: '变动方向', ...required }),
  movement_type: Field.select([
    { value: 'opening_inbound', label: '期初入库' }, { value: 'purchase_inbound', label: '采购入库' },
    { value: 'production_issue', label: '生产领料' }, { value: 'production_supply', label: '生产补料' },
    { value: 'production_return', label: '生产退料' }, { value: 'production_inbound', label: '生产入库' },
    { value: 'disassembly_outbound', label: '拆解成品出库' }, { value: 'disassembly_recovery', label: '拆解物料回收' },
    { value: 'replacement_issue', label: '换件新件领用' }, { value: 'replacement_recovery', label: '换件旧件回收' },
    { value: 'sales_outbound', label: '销售出库' }, { value: 'purchase_return_outbound', label: '采购退货出库' },
    { value: 'purchase_replacement_inbound', label: '采购换货补货入库' },
    { value: 'subcontract_issue_outbound', label: '委外发料出库' },
    { value: 'subcontract_receipt_inbound', label: '委外回厂入库' },
    { value: 'subcontract_ncr_concession', label: '委外特采入库' },
    { value: 'adjustment', label: '库存调整' },
  ], { label: '流水类型', ...required }),
  quantity: quantity('变动数量', true), before_on_hand: quantity('变动前库存'), after_on_hand: quantity('变动后库存'),
  before_available: quantity('变动前可用库存'), after_available: quantity('变动后可用库存'),
  unit_cost: nonNegativeMoney('含税单位成本'), amount: nonNegativeMoney('含税金额'), occurred_at: Field.datetime({ label: '发生时间', ...required }),
  source_object: text('来源对象', true), source_id: text('来源记录ID', true), source_line_id: text('来源明细ID'),
  responsible_id: owner(true), remarks: remarks(),
}, ['code', 'occurred_at', 'warehouse_id', 'sku_id', 'direction', 'movement_type', 'quantity', 'before_on_hand', 'after_on_hand', 'source_object', 'source_id']);
